import { ElectricalComponentData, ElectricalSystemId, ElectricalSystemMeta } from './types';

export const ELECTRICAL_SYSTEM_METAS: ElectricalSystemMeta[] = [
  {
    id: 'battery',
    nameEn: 'Battery & Primary Power',
    nameAr: 'البطارية ومصدر الطاقة الأساسي',
    icon: 'battery_charging_full',
    voltageClass: 'High-Amperage (>50A)',
    description: '12V Primary Storage, Fusible Link Block, and High-Resolution Intelligent Battery Sensor (IBS).',
  },
  {
    id: 'alternator',
    nameEn: 'Alternator & Charging',
    nameAr: 'المولد ونظام الشحن (الدينمو)',
    icon: 'sync',
    voltageClass: 'High-Amperage (>50A)',
    description: '150A Segment-Conductor Hairpin Stator, 12-Diode Bridge Rectifier, and LIN-bus Monitored Voltage Regulator.',
  },
  {
    id: 'starter',
    nameEn: 'Starter & Cranking Circuit',
    nameAr: 'بادئ الحركة ودائرة السلف',
    icon: 'speed',
    voltageClass: 'High-Amperage (>50A)',
    description: '1.4kW Planetary Gear Reduction Starter with dual Pull-in / Hold-in Solenoid Coils and Terminal 50 logic.',
  },
  {
    id: 'fuses',
    nameEn: 'Fuses & Junction Blocks',
    nameAr: 'الفيوزات وصناديق التوزيع (علبة الفيوزات)',
    icon: 'safety_check',
    voltageClass: '12V Primary',
    description: 'Engine Compartment Fuse Box (Type A) and Cabin Driver-side J/B with Low-Profile Mini and JCASE links.',
  },
  {
    id: 'relays',
    nameEn: 'Relays & Power Switching',
    nameAr: 'المرحلات (الكتاوت) ودوائر التحويل',
    icon: 'electrical_services',
    voltageClass: '12V Primary',
    description: 'ISO Micro & Mini Relays controlling EFI Main, Starter, A/C Magnetic Clutch, and High-Beam Headlamps.',
  },
  {
    id: 'lighting',
    nameEn: 'Lighting & Headlamps',
    nameAr: 'الإضاءة والأنوار الأمامية والخلفية',
    icon: 'lightbulb',
    voltageClass: '12V Primary',
    description: 'Bi-Beam LED Projectors, High-Beam Shutter Solenoid, DRL Light Guide, and Combination Switch circuits.',
  },
  {
    id: 'ignition',
    nameEn: 'Ignition & COP Coils',
    nameAr: 'نظام الإشعال وكويلات شمعات الاحتراق',
    icon: 'bolt',
    voltageClass: 'Pulsed High-Voltage',
    description: 'Direct Coil-On-Plug (COP) 4-pin architecture with +12V power, Ground, IGT Trigger, and IGF Confirmation.',
  },
  {
    id: 'sensors',
    nameEn: 'Sensors & 5V Reference',
    nameAr: 'الحساسات وشبكة المرجع 5 فولت (VREF)',
    icon: 'sensors',
    voltageClass: '5V Logic',
    description: 'Crankshaft Position (CKP), Mass Airflow (MAF), Intake Temp (IAT), and Throttle Position (TPS) networks.',
  },
  {
    id: 'ecu',
    nameEn: 'Engine Control Module (ECM)',
    nameAr: 'كمبيوتر المحرك (ECU / ECM)',
    icon: 'memory',
    voltageClass: '5V Logic',
    description: 'Main Powertrain Control Module with 128-pin harness, power grounds, and low-side driver circuits.',
  },
  {
    id: 'can-bus',
    nameEn: 'CAN Bus & Diagnostics',
    nameAr: 'شبكة الكان باص وخط الفحص (CAN Bus)',
    icon: 'hub',
    voltageClass: 'CAN Bus Differential',
    description: 'ISO 11898-2 High-Speed 500 kbps Differential Bus with 120Ω terminating resistors and DLC3 OBD-II connector.',
  },
];

export const TOYOTA_CAMRY_COMPONENTS: Record<ElectricalSystemId, ElectricalComponentData[]> = {
  battery: [
    {
      id: 'toyota-battery-pack',
      systemId: 'battery',
      nameEn: '12V Lead-Acid Battery & Fusible Link Hub',
      nameAr: 'بطارية 12 فولت ومجمع فيوزات القدرة الرئيسية',
      location: 'Engine Bay, Front Left (Driver Side)',
      partNumberOEM: '28800-21060 (Group 35 / 640 CCA)',
      powerPath: {
        summary: 'Direct B+ 12V terminal feed through 150A primary bolt-on fusible link into Engine Room Junction Block.',
        sourceNode: 'B+ Battery Positive Post (12.6V OCV)',
        fuseNode: '150A MAIN Fusible Link (Bolt-on busbar)',
        relayNode: 'Engine Room Main Bus',
        wireColorCode: 'R (Red, 0 AWG heavy primary copper)',
        wireColorHex: '#ef4444',
        wireGauge: '0 AWG (53.5 mm²)',
        connectorCode: 'Terminal Clamp B1',
        terminalPin: 'Post Bolt M8 (Torque 5.4 Nm)',
      },
      ground: {
        summary: 'Heavy 2 AWG battery negative cable bolted directly to chassis inner fender (Ground Point EA) and engine block.',
        terminalPin: 'Negative Terminal Clamp (-)',
        groundPointId: 'EA & EB (Body Fender & Transmission Case)',
        location: 'Left Front Fender Apron & Transaxle Ground Boss',
        wireColorCode: 'W-B (White with Black stripe)',
        wireColorHex: '#f8fafc',
        maxResistanceOhms: 0.03,
      },
      signal: {
        summary: 'Battery Current & Temperature Sensor monitors state of charge via LIN Bus single-wire communication to ECM.',
        signalType: 'LIN Single-Wire',
        controller: 'ECM (Engine Control Module)',
        controllerPin: 'E24-38 (LIN1 / BATT_STAT)',
        wireColorCode: 'Y-G (Yellow with Green stripe)',
        wireColorHex: '#eab308',
        operatingRange: 'LIN 2.0 protocol (19.2 kbps, 0-12V logic pulses)',
        waveformDesc: 'Dominant 0V, Recessive 12V pulse packets every 100ms',
      },
      relatedFuse: {
        id: 'MAIN-FL-150A',
        name: 'Fusible Link Block No. 1 (ALT / MAIN)',
        ratingAmps: 150,
        fuseType: 'Bolt-on Fusible Link',
        locationBox: 'Directly bolted to positive battery terminal shoe',
        colorHex: '#3b82f6',
      },
      relatedRelay: {
        id: 'BATT-ISOLATOR',
        name: 'Primary Power Distribution Bus',
        type: 'Solid-State Smart Driver',
        location: 'Engine Room Junction Block No. 1',
        coilTerminals: 'Solid busbar (Permanent Connection)',
        contactTerminals: 'Direct Feed to Cabin J/B & Alternator',
        nominalCoilOhms: 0,
      },
      relatedSensor: {
        id: 'IBS-28850',
        name: 'Intelligent Battery State-of-Charge Sensor',
        partNumberOEM: '28850-25010',
        sensorTechnology: 'Active Shunt Resistor',
        diagnosticRole: 'Measures battery net charge/discharge current (±200A), post temperature, and terminal voltage for smart alternator control.',
        normalOperatingValue: '+1.5A to +15.0A Charging, 25°C - 45°C temp',
      },
      testValues: {
        voltage: {
          keyOffV: 12.6,
          keyOnV: 12.2,
          runningV: 14.2,
          vrefV: 12.6,
          nominalText: '12.6V Key OFF (100% SOC), 14.1V - 14.4V Engine Running',
        },
        resistance: {
          nominalOhms: 0.005,
          minOhms: 0.002,
          maxOhms: 0.012,
          testCondition: 'Negative post to engine block bare metal (Ohm mode)',
        },
        continuity: {
          testPinA: 'Battery Neg Post',
          testPinB: 'Ground Point EA (Chassis Sheet)',
          expectedLoopOhms: 0.02,
          status: 'CONTINUITY OK (< 0.1 Ω)',
        },
        voltageDrop: {
          testCircuit: 'Battery Positive Post to Alternator B+ Stud under 60A load',
          standardMaxV: 0.2,
          measuredDropV: 0.08,
          standardRef: 'SAE J1114 Cranking & Charging Standard',
          passStatus: true,
        },
      },
      schematic: {
        nodes: [
          { id: 'bat-pos', label: '12V Battery (+)', sub: '12.6V Post', x: 80, y: 150, type: 'battery' },
          { id: 'fuse-main', label: '150A Fusible Link', sub: 'ALT/MAIN', x: 220, y: 150, type: 'fuse' },
          { id: 'jb-bus', label: 'Engine Bay J/B', sub: 'Bus Feed', x: 380, y: 150, type: 'switch_ecu' },
          { id: 'load-sys', label: 'Vehicle Electrical System', sub: 'All Branches', x: 550, y: 150, type: 'component' },
          { id: 'gnd-ea', label: 'Ground EA', sub: 'Chassis Fender', x: 550, y: 280, type: 'ground' },
          { id: 'bat-neg', label: 'Battery Neg (-)', sub: 'Ground Strap', x: 80, y: 280, type: 'ground' },
        ],
        wires: [
          { fromNodeId: 'bat-pos', toNodeId: 'fuse-main', wireType: 'power', colorCode: 'R (0 AWG)', colorHex: '#ef4444', gaugeAwg: '0 AWG', voltageNominalV: 12.6, expectedCurrentA: 45 },
          { fromNodeId: 'fuse-main', toNodeId: 'jb-bus', wireType: 'power', colorCode: 'R (4 AWG)', colorHex: '#ef4444', gaugeAwg: '4 AWG', voltageNominalV: 12.58, expectedCurrentA: 45 },
          { fromNodeId: 'jb-bus', toNodeId: 'load-sys', wireType: 'power', colorCode: 'W-R (8 AWG)', colorHex: '#f87171', gaugeAwg: '8 AWG', voltageNominalV: 12.55, expectedCurrentA: 25 },
          { fromNodeId: 'load-sys', toNodeId: 'gnd-ea', wireType: 'ground', colorCode: 'W-B (4 AWG)', colorHex: '#cbd5e1', gaugeAwg: '4 AWG', voltageNominalV: 0.04, expectedCurrentA: 25 },
          { fromNodeId: 'gnd-ea', toNodeId: 'bat-neg', wireType: 'ground', colorCode: 'W-B (2 AWG)', colorHex: '#f8fafc', gaugeAwg: '2 AWG', voltageNominalV: 0.02, expectedCurrentA: 45 },
        ],
      },
    },
  ],

  alternator: [
    {
      id: 'toyota-alternator-denso',
      systemId: 'alternator',
      nameEn: 'Denso 150A Hairpin Alternator with LIN Regulator',
      nameAr: 'دينمو الشحن دينسو 150 أمبير بنظام تحكم LIN',
      location: 'Engine Front Accessory Belt Drive, Lower Right',
      partNumberOEM: '27060-25090 (12V 150A Denso SC6)',
      powerPath: {
        summary: 'Heavy 4 AWG B+ output cable bolted to alternator M8 output stud routed to 150A ALT fuse and battery positive.',
        sourceNode: 'Alternator Stator B+ Output Stud (M8)',
        fuseNode: '150A ALT Fuse (Fusible Link Block)',
        relayNode: 'Internal Diode Rectifier Bridge',
        wireColorCode: 'B (Black with Red heat-shrink)',
        wireColorHex: '#dc2626',
        wireGauge: '4 AWG (21.2 mm²)',
        connectorCode: 'Terminal B Stud & Connector A19',
        terminalPin: 'Pin 1 (B+ Stud), Pin 2 (LIN/COM)',
      },
      ground: {
        summary: 'Direct metallic case contact to engine front bracket, returning through cylinder head ground cable EB.',
        terminalPin: 'Alternator Metal Housing Bracket',
        groundPointId: 'EB (Cylinder Block Ground Boss)',
        location: 'Lower Front Engine Timing Cover Ground',
        wireColorCode: 'Direct Metallic Bond',
        wireColorHex: '#94a3b8',
        maxResistanceOhms: 0.02,
      },
      signal: {
        summary: 'ECM controls field excitation via LIN 2.0 communication (Connector A19 Pin 1), modulating charging between 12.8V and 14.7V based on electrical load.',
        signalType: 'LIN Single-Wire',
        controller: 'ECM (Engine Control Module)',
        controllerPin: 'Connector E24 Pin 41 (ALTT / LIN)',
        wireColorCode: 'L-Y (Blue with Yellow stripe)',
        wireColorHex: '#38bdf8',
        operatingRange: 'PWM Duty Cycle / LIN commands (12.8V - 14.7V setpoint)',
        waveformDesc: 'LIN Bus bit packets (19.2 kbps baud rate)',
      },
      relatedFuse: {
        id: 'ALT-S-7.5A',
        name: 'ALT-S (Alternator Voltage Sensing Fuse)',
        ratingAmps: 7.5,
        fuseType: 'Low-Profile Mini',
        locationBox: 'Engine Room Junction Block (Slot F3)',
        colorHex: '#a855f7',
      },
      relatedRelay: {
        id: 'IG2-RELAY',
        name: 'IG2 Main Ignition Relay (Wakes Voltage Regulator)',
        type: '4-Pin SPST',
        location: 'Engine Room Junction Block, Position R4',
        coilTerminals: 'Pin 85 (GND) & Pin 86 (+12V IG Switched)',
        contactTerminals: 'Pin 30 (B+ Hot) & Pin 87 (Ignition Feed to A19 Pin 2)',
        nominalCoilOhms: 82,
      },
      relatedSensor: {
        id: 'BATT-TEMP-SENSOR',
        name: 'Battery Post Temperature Sensor',
        partNumberOEM: '28850-25010',
        sensorTechnology: 'NTC Thermistor',
        diagnosticRole: 'Prevents battery overcharging boiling: reduces alternator voltage setpoint at high ambient temperatures (>40°C).',
        normalOperatingValue: '2.5 kΩ at 25°C, V_set = 14.2V; 1.0 kΩ at 50°C, V_set = 13.6V',
      },
      testValues: {
        voltage: {
          keyOffV: 12.6,
          keyOnV: 12.4,
          runningV: 14.25,
          vrefV: 12.6,
          nominalText: '13.8V - 14.5V under normal load, 14.7V during decel regeneration',
        },
        resistance: {
          nominalOhms: 2.1,
          minOhms: 1.8,
          maxOhms: 2.5,
          testCondition: 'Rotor slip rings field coil resistance at 20°C',
        },
        continuity: {
          testPinA: 'Alternator Case Metal',
          testPinB: 'Battery Negative Post',
          expectedLoopOhms: 0.03,
          status: 'CONTINUITY OK (< 0.1 Ω)',
        },
        voltageDrop: {
          testCircuit: 'Alternator B+ Stud to Battery Positive Post at 80A full electrical load',
          standardMaxV: 0.3,
          measuredDropV: 0.12,
          standardRef: 'SAE J56 / ISO 8854 Alternator Specification',
          passStatus: true,
        },
      },
      schematic: {
        nodes: [
          { id: 'alt-gen', label: 'Alternator Stator & Bridge', sub: '14.2V Source', x: 80, y: 150, type: 'component' },
          { id: 'fuse-alt', label: '150A ALT Fuse', sub: 'Fusible Link Block', x: 230, y: 150, type: 'fuse' },
          { id: 'bat-store', label: '12V Battery (+)', sub: 'Storage Reservoir', x: 400, y: 150, type: 'battery' },
          { id: 'ecm-lin', label: 'ECM (LIN Regulator)', sub: 'Duty Setpoint', x: 80, y: 280, type: 'switch_ecu' },
          { id: 'gnd-block', label: 'Engine Ground EB', sub: 'Direct Case Mount', x: 400, y: 280, type: 'ground' },
        ],
        wires: [
          { fromNodeId: 'alt-gen', toNodeId: 'fuse-alt', wireType: 'power', colorCode: 'B (4 AWG)', colorHex: '#dc2626', gaugeAwg: '4 AWG', voltageNominalV: 14.25, expectedCurrentA: 65 },
          { fromNodeId: 'fuse-alt', toNodeId: 'bat-store', wireType: 'power', colorCode: 'R (0 AWG)', colorHex: '#ef4444', gaugeAwg: '0 AWG', voltageNominalV: 14.18, expectedCurrentA: 65 },
          { fromNodeId: 'ecm-lin', toNodeId: 'alt-gen', wireType: 'signal', colorCode: 'L-Y (LIN Bus)', colorHex: '#38bdf8', gaugeAwg: '20 AWG', voltageNominalV: 12.0, expectedCurrentA: 0.05 },
          { fromNodeId: 'alt-gen', toNodeId: 'gnd-block', wireType: 'ground', colorCode: 'Engine Case Boss', colorHex: '#94a3b8', gaugeAwg: 'Bond', voltageNominalV: 0.03, expectedCurrentA: 65 },
        ],
      },
    },
  ],

  starter: [
    {
      id: 'toyota-starter-motor',
      systemId: 'starter',
      nameEn: 'Planetary Gear Reduction Starter & Dual-Coil Solenoid',
      nameAr: 'مارش التشغيل (السلف) بالتروس الكوكبية وسولينويد مزدوج',
      location: 'Engine Rear Left, Mounted to Transmission Bellhousing',
      partNumberOEM: '28100-25030 (12V 1.4kW Denso TS-type)',
      powerPath: {
        summary: 'Unfused 2 AWG primary cable feeds 30 Terminal directly from Battery (+). 30A ST fuse feeds starter relay to energize 50 Terminal pull-in coil.',
        sourceNode: 'Battery Positive 30 Terminal (High Amp)',
        fuseNode: '30A ST Fuse (Engine Room J/B)',
        relayNode: 'STARTER RELAY (ST RELAY)',
        wireColorCode: 'B (Black 2 AWG main) / B-R (Black/Red 12 AWG trigger)',
        wireColorHex: '#1e293b',
        wireGauge: '2 AWG (Primary) & 12 AWG (Control 50)',
        connectorCode: 'Terminal 30 Bolt & Terminal 50 Connector C12',
        terminalPin: 'Terminal 30 (M8 Nut), Terminal 50 (Slide Lock Pin 1)',
      },
      ground: {
        summary: 'Starter motor flange directly grounded to aluminum transaxle bellhousing, returning through 2 AWG engine ground cable EB.',
        terminalPin: 'Starter Mounting Flange',
        groundPointId: 'EB (Transaxle Case Ground Cable)',
        location: 'Transaxle Upper Bellhousing to Chassis Strut Tower',
        wireColorCode: 'Heavy Braided Copper Strap',
        wireColorHex: '#cbd5e1',
        maxResistanceOhms: 0.015,
      },
      signal: {
        summary: 'Push-Button Start / Smart Key ECU commands ECM Pin E24-12 to pull Starter Relay coil to ground, delivering +12V to Terminal 50.',
        signalType: '12V Switched',
        controller: 'ECM (Engine Control Module) & Smart Key ECU',
        controllerPin: 'Connector E24 Pin 12 (STAR / Starter Control)',
        wireColorCode: 'W-R (White with Red stripe)',
        wireColorHex: '#fca5a5',
        operatingRange: '0V Key OFF, 12.0V during Start request',
        waveformDesc: 'DC Step: 12V pulse held for duration of cranking (0.8s typical)',
      },
      relatedFuse: {
        id: 'ST-30A',
        name: 'ST (Starter Solenoid Fuse)',
        ratingAmps: 30,
        fuseType: 'JCASE Cartridge',
        locationBox: 'Engine Room Junction Block (Slot F12)',
        colorHex: '#10b981',
      },
      relatedRelay: {
        id: 'ST-RELAY',
        name: 'STARTER RELAY (ST)',
        type: '4-Pin SPST',
        location: 'Engine Room Junction Block, Position R1',
        coilTerminals: 'Pin 85 (ECM Controlled Ground) & Pin 86 (Ignition +12V)',
        contactTerminals: 'Pin 30 (Fused B+ from 30A ST) & Pin 87 (To Starter Terminal 50)',
        nominalCoilOhms: 78,
      },
      relatedSensor: {
        id: 'PNP-SWITCH',
        name: 'Park/Neutral Position Switch (Transmission Inhibitor)',
        partNumberOEM: '84540-33010',
        sensorTechnology: 'Dual Potentiometer',
        diagnosticRole: 'Safety interlock: prevents starter relay activation unless transaxle selector is physically verified in P (Park) or N (Neutral).',
        normalOperatingValue: '0 Ω continuity in Park/Neutral; Open circuit in Drive/Reverse',
      },
      testValues: {
        voltage: {
          keyOffV: 12.6,
          keyOnV: 12.2,
          runningV: 10.2, // during crank
          vrefV: 12.0,
          nominalText: 'Terminal 30: 12.6V resting, >9.6V during crank; Terminal 50: 11.5V when cranking',
        },
        resistance: {
          nominalOhms: 0.85,
          minOhms: 0.7,
          maxOhms: 1.1,
          testCondition: 'Terminal 50 pull-in & hold-in coil resistance to case ground at 20°C',
        },
        continuity: {
          testPinA: 'Terminal 50 Pin',
          testPinB: 'Solenoid Case Ground',
          expectedLoopOhms: 0.9,
          status: 'CONTINUITY OK (< 0.1 Ω)',
        },
        voltageDrop: {
          testCircuit: 'Battery Positive Post to Starter Terminal 30 during 180A Cranking Inrush',
          standardMaxV: 0.25,
          measuredDropV: 0.14,
          standardRef: 'SAE J1114 Cranking Motor Test Spec',
          passStatus: true,
        },
      },
      schematic: {
        nodes: [
          { id: 'bat-pos', label: '12V Battery (+)', sub: '2 AWG Direct B+', x: 60, y: 120, type: 'battery' },
          { id: 'fuse-st', label: '30A ST Fuse', sub: 'Engine J/B', x: 200, y: 220, type: 'fuse' },
          { id: 'st-relay', label: 'ST Relay', sub: 'Contacts 30/87', x: 340, y: 220, type: 'relay' },
          { id: 'ecm-ctrl', label: 'ECM & Park/Neutral', sub: 'Start Trigger', x: 340, y: 320, type: 'switch_ecu' },
          { id: 'st-motor', label: 'Starter Motor & Solenoid', sub: 'Term 30 & Term 50', x: 500, y: 160, type: 'component' },
          { id: 'gnd-block', label: 'Bellhousing Ground', sub: 'Engine Boss EB', x: 500, y: 300, type: 'ground' },
        ],
        wires: [
          { fromNodeId: 'bat-pos', toNodeId: 'st-motor', wireType: 'power', colorCode: 'B (2 AWG)', colorHex: '#1e293b', gaugeAwg: '2 AWG', voltageNominalV: 12.6, expectedCurrentA: 180 },
          { fromNodeId: 'bat-pos', toNodeId: 'fuse-st', wireType: 'power', colorCode: 'R (12 AWG)', colorHex: '#ef4444', gaugeAwg: '12 AWG', voltageNominalV: 12.5, expectedCurrentA: 18 },
          { fromNodeId: 'fuse-st', toNodeId: 'st-relay', wireType: 'power', colorCode: 'B-R (12 AWG)', colorHex: '#f87171', gaugeAwg: '12 AWG', voltageNominalV: 12.45, expectedCurrentA: 18 },
          { fromNodeId: 'st-relay', toNodeId: 'st-motor', wireType: 'power', colorCode: 'B-W (Term 50)', colorHex: '#38bdf8', gaugeAwg: '12 AWG', voltageNominalV: 11.8, expectedCurrentA: 18 },
          { fromNodeId: 'ecm-ctrl', toNodeId: 'st-relay', wireType: 'signal', colorCode: 'W-R (Coil Trigger)', colorHex: '#fca5a5', gaugeAwg: '20 AWG', voltageNominalV: 12.0, expectedCurrentA: 0.15 },
          { fromNodeId: 'st-motor', toNodeId: 'gnd-block', wireType: 'ground', colorCode: 'Flange to Bellhousing', colorHex: '#cbd5e1', gaugeAwg: 'Bond', voltageNominalV: 0.08, expectedCurrentA: 180 },
        ],
      },
    },
  ],

  fuses: [
    {
      id: 'toyota-fuse-block-engine',
      systemId: 'fuses',
      nameEn: 'Engine Compartment Fuse & Relay Junction Block (Type A)',
      nameAr: 'علبة فيوزات ومرحلات حجرة المحرك الرئيسية (نوع A)',
      location: 'Engine Bay, Front Left adjacent to battery',
      partNumberOEM: '82720-33310 (Engine Room Junction Block No. 1)',
      powerPath: {
        summary: 'Direct copper busbar link from battery positive distribution terminal into multi-tier blade and cartridge fuses.',
        sourceNode: 'Main B+ Busbar from Fusible Link 150A',
        fuseNode: 'Integrated Busbar distribution to 32 fuse cavities',
        relayNode: 'Integrated PCB Solid-State Matrix',
        wireColorCode: 'R (Continuous Heavy Busbar)',
        wireColorHex: '#ef4444',
        wireGauge: 'Stamped Copper Busbar (2.0mm thickness)',
        connectorCode: 'Connectors 1A, 1B, 1C, 1D',
        terminalPin: 'Main Input Lug (Bolt M8)',
      },
      ground: {
        summary: 'Multiple internal electronics ground pins connected via harness wire W-B to left inner fender ground bolt EA.',
        terminalPin: 'Connector 1B Pin 12',
        groundPointId: 'EA (Left Front Inner Fender)',
        location: 'Adjacent to Washer Fluid Reservoir Neck',
        wireColorCode: 'W-B (White with Black stripe)',
        wireColorHex: '#f8fafc',
        maxResistanceOhms: 0.05,
      },
      signal: {
        summary: 'CAN Gateway and LIN bus links for intelligent power switching and smart fuse diagnostics.',
        signalType: 'Differential CAN (2.5V/3.5V)',
        controller: 'Main Body ECU (Multiplex Network Body ECU)',
        controllerPin: 'Connector 1D Pin 8 (CAN_H) & Pin 9 (CAN_L)',
        wireColorCode: 'W (CAN_H) & B (CAN_L)',
        wireColorHex: '#fbbf24',
        operatingRange: '500 kbps Differential (2.5V baseline)',
        waveformDesc: 'CAN high/low differential square wave packets',
      },
      relatedFuse: {
        id: 'ECU-B2-10A',
        name: 'ECU-B2 (Continuous ECM Memory Power)',
        ratingAmps: 10,
        fuseType: 'Low-Profile Mini',
        locationBox: 'Engine Room Junction Block, Position F18',
        colorHex: '#ef4444',
      },
      relatedRelay: {
        id: 'MAIN-EFI-RELAY',
        name: 'EFI MAIN RELAY',
        type: '4-Pin SPST',
        location: 'Engine Room Junction Block, Position R3',
        coilTerminals: 'Pin 85 (GND) & Pin 86 (Switched Power)',
        contactTerminals: 'Pin 30 (B+ Hot) & Pin 87 (Feeds injectors & coils)',
        nominalCoilOhms: 85,
      },
      relatedSensor: {
        id: 'UNDERHOOD-TEMP-SENSOR',
        name: 'Ambient Underhood Junction Box Thermistor',
        partNumberOEM: '88625-48020',
        sensorTechnology: 'NTC Thermistor',
        diagnosticRole: 'Monitors relay box temperature to trigger cooling fans under high thermal soak conditions.',
        normalOperatingValue: '1.8 kΩ at 30°C',
      },
      testValues: {
        voltage: {
          keyOffV: 12.6,
          keyOnV: 12.3,
          runningV: 14.2,
          vrefV: 12.6,
          nominalText: '12.6V across primary busbar, <0.02V drop across each fuse element',
        },
        resistance: {
          nominalOhms: 0.02,
          minOhms: 0.005,
          maxOhms: 0.05,
          testCondition: 'Fuse blade test tabs across 10A fuse element',
        },
        continuity: {
          testPinA: 'Fuse Test Tab 1',
          testPinB: 'Fuse Test Tab 2',
          expectedLoopOhms: 0.01,
          status: 'CONTINUITY OK (< 0.1 Ω)',
        },
        voltageDrop: {
          testCircuit: 'Main Battery Terminal to Fuse F18 Output Terminal under 8A load',
          standardMaxV: 0.15,
          measuredDropV: 0.04,
          standardRef: 'SAE J2077 Blade Type Fuse Standard',
          passStatus: true,
        },
      },
      schematic: {
        nodes: [
          { id: 'bus-in', label: 'Primary B+ Bus', sub: '12.6V Feed', x: 80, y: 150, type: 'battery' },
          { id: 'f18', label: '10A ECU-B2', sub: 'Cavity F18', x: 230, y: 100, type: 'fuse' },
          { id: 'f22', label: '15A H-LP', sub: 'Cavity F22', x: 230, y: 180, type: 'fuse' },
          { id: 'f30', label: '30A ST Cartridge', sub: 'Cavity F30', x: 230, y: 260, type: 'fuse' },
          { id: 'load-branch', label: 'Cabin & Engine Harnesses', sub: 'Branch Circuits', x: 420, y: 180, type: 'component' },
          { id: 'gnd-ea', label: 'Ground EA', sub: 'Fender Bolt', x: 420, y: 280, type: 'ground' },
        ],
        wires: [
          { fromNodeId: 'bus-in', toNodeId: 'f18', wireType: 'power', colorCode: 'Busbar Link', colorHex: '#ef4444', gaugeAwg: 'Bus', voltageNominalV: 12.6, expectedCurrentA: 5 },
          { fromNodeId: 'bus-in', toNodeId: 'f22', wireType: 'power', colorCode: 'Busbar Link', colorHex: '#ef4444', gaugeAwg: 'Bus', voltageNominalV: 12.6, expectedCurrentA: 12 },
          { fromNodeId: 'bus-in', toNodeId: 'f30', wireType: 'power', colorCode: 'Busbar Link', colorHex: '#ef4444', gaugeAwg: 'Bus', voltageNominalV: 12.6, expectedCurrentA: 25 },
          { fromNodeId: 'f22', toNodeId: 'load-branch', wireType: 'power', colorCode: 'W-R (14 AWG)', colorHex: '#f87171', gaugeAwg: '14 AWG', voltageNominalV: 12.58, expectedCurrentA: 12 },
          { fromNodeId: 'load-branch', toNodeId: 'gnd-ea', wireType: 'ground', colorCode: 'W-B (14 AWG)', colorHex: '#cbd5e1', gaugeAwg: '14 AWG', voltageNominalV: 0.02, expectedCurrentA: 12 },
        ],
      },
    },
  ],

  relays: [
    {
      id: 'toyota-efi-main-relay',
      systemId: 'relays',
      nameEn: 'EFI Main Relay (Engine Fuel & Electronics Power)',
      nameAr: 'مرحل نظام حقن الوقود الرئيسي (EFI MAIN RELAY)',
      location: 'Engine Room Junction Block, Cavity R3',
      partNumberOEM: '90987-02028 (Denso 12V 4-Pin SPST)',
      powerPath: {
        summary: 'Constant B+ enters Terminal 30 via 25A EFI-MAIN fuse. When energized, internal contacts close to deliver 12V out Terminal 87 to injectors and ECM.',
        sourceNode: '25A EFI-MAIN Fuse',
        fuseNode: '25A EFI-MAIN Fuse',
        relayNode: 'Contacts 30 (Input) -> 87 (Output)',
        wireColorCode: 'B-W (Black with White stripe)',
        wireColorHex: '#334155',
        wireGauge: '14 AWG (2.0 mm²)',
        connectorCode: 'Relay Socket Cavity R3',
        terminalPin: 'Pin 30 (B+ Hot) & Pin 87 (Load Feed)',
      },
      ground: {
        summary: 'Coil Pin 85 is grounded directly via ECM Pin E24-2 (MREL control logic) or hard-wired to chassis ground Point EA.',
        terminalPin: 'Pin 85 (Relay Coil Ground)',
        groundPointId: 'EA (Left Front Fender)',
        location: 'Inner Fender Apron Ground Terminal',
        wireColorCode: 'W-B (White with Black stripe)',
        wireColorHex: '#f8fafc',
        maxResistanceOhms: 0.04,
      },
      signal: {
        summary: 'When Ignition Switch is turned ON, ECM energizes MREL driver, providing 12V to Coil Pin 86 and pulling internal magnetic armature closed.',
        signalType: '12V Switched',
        controller: 'ECM (Engine Control Module)',
        controllerPin: 'Connector E24 Pin 1 (MREL / Main Relay Enable)',
        wireColorCode: 'B-Y (Black with Yellow stripe)',
        wireColorHex: '#ca8a04',
        operatingRange: '0V Key OFF, 12.2V Key ON',
        waveformDesc: 'Static 12V DC enable latch when ignition is live',
      },
      relatedFuse: {
        id: 'EFI-MAIN-25A',
        name: 'EFI-MAIN Fuse',
        ratingAmps: 25,
        fuseType: 'Low-Profile Mini',
        locationBox: 'Engine Room Junction Block (Slot F2)',
        colorHex: '#3b82f6',
      },
      relatedRelay: {
        id: 'EFI-MAIN-SPST',
        name: 'EFI MAIN Micro ISO Relay',
        type: '4-Pin SPST',
        location: 'Engine Room Junction Block, Position R3',
        coilTerminals: 'Pin 85 (GND) & Pin 86 (MREL +12V from ECM)',
        contactTerminals: 'Pin 30 (Hot at all times from 25A fuse) & Pin 87 (Output to ECM +B)',
        nominalCoilOhms: 84,
      },
      relatedSensor: {
        id: 'IGNITION-SW-ACC',
        name: 'Push-Button Start Switch (IG1 Confirmation)',
        partNumberOEM: '89611-33040',
        sensorTechnology: 'Dual Potentiometer',
        diagnosticRole: 'Provides primary human operator power request confirmation to Power Source Control ECU.',
        normalOperatingValue: 'Normally Open; 0 Ω continuity upon switch depression',
      },
      testValues: {
        voltage: {
          keyOffV: 0.0,
          keyOnV: 12.2,
          runningV: 14.15,
          vrefV: 12.0,
          nominalText: 'Pin 30: 12.6V constant; Pin 86: 12.2V Key ON; Pin 87: 12.2V active',
        },
        resistance: {
          nominalOhms: 84,
          minOhms: 75,
          maxOhms: 95,
          testCondition: 'Between Relay Coil Pins 85 and 86 at 20°C',
        },
        continuity: {
          testPinA: 'Relay Pin 30',
          testPinB: 'Relay Pin 87 (De-energized)',
          expectedLoopOhms: 999999, // Open
          status: 'OPEN CIRCUIT',
        },
        voltageDrop: {
          testCircuit: 'Across closed contacts (Pin 30 to Pin 87) under 15A active engine load',
          standardMaxV: 0.2,
          measuredDropV: 0.06,
          standardRef: 'SAE J2544 Automotive Relay Test Specification',
          passStatus: true,
        },
      },
      schematic: {
        nodes: [
          { id: 'f2-fuse', label: '25A EFI Fuse', sub: 'B+ Hot', x: 80, y: 120, type: 'fuse' },
          { id: 'r3-coil', label: 'Relay Coil 85/86', sub: '84 Ω Magnetic', x: 260, y: 220, type: 'relay' },
          { id: 'r3-contacts', label: 'Contacts 30/87', sub: 'SPST Switch', x: 260, y: 120, type: 'relay' },
          { id: 'ecm-mrel', label: 'ECM MREL Pin 1', sub: '12V Coil Drive', x: 80, y: 220, type: 'switch_ecu' },
          { id: 'load-ecm', label: 'ECM +B & Injectors', sub: 'Active Load', x: 440, y: 120, type: 'component' },
          { id: 'gnd-ea', label: 'Chassis Ground EA', sub: 'Fender Lug', x: 440, y: 220, type: 'ground' },
        ],
        wires: [
          { fromNodeId: 'f2-fuse', toNodeId: 'r3-contacts', wireType: 'power', colorCode: 'B-W (14 AWG)', colorHex: '#ef4444', gaugeAwg: '14 AWG', voltageNominalV: 12.6, expectedCurrentA: 14 },
          { fromNodeId: 'ecm-mrel', toNodeId: 'r3-coil', wireType: 'signal', colorCode: 'B-Y (20 AWG)', colorHex: '#ca8a04', gaugeAwg: '20 AWG', voltageNominalV: 12.2, expectedCurrentA: 0.14 },
          { fromNodeId: 'r3-coil', toNodeId: 'gnd-ea', wireType: 'ground', colorCode: 'W-B (20 AWG)', colorHex: '#cbd5e1', gaugeAwg: '20 AWG', voltageNominalV: 0.02, expectedCurrentA: 0.14 },
          { fromNodeId: 'r3-contacts', toNodeId: 'load-ecm', wireType: 'power', colorCode: 'B-R (14 AWG)', colorHex: '#f87171', gaugeAwg: '14 AWG', voltageNominalV: 12.54, expectedCurrentA: 14 },
          { fromNodeId: 'load-ecm', toNodeId: 'gnd-ea', wireType: 'ground', colorCode: 'W-B (12 AWG)', colorHex: '#f8fafc', gaugeAwg: '12 AWG', voltageNominalV: 0.04, expectedCurrentA: 14 },
        ],
      },
    },
  ],

  lighting: [
    {
      id: 'toyota-bi-beam-led',
      systemId: 'lighting',
      nameEn: 'Bi-Beam LED Headlamp & High-Beam Shutter Assembly',
      nameAr: 'مجموعة المصابيح الأمامية LED ثنائية الإضاءة مع قاطع العالي',
      location: 'Front Left & Right Headlamp Clusters',
      partNumberOEM: '81110-06C40 (Left Bi-Beam Projector Headlamp)',
      powerPath: {
        summary: '15A H-LP LH fuse feeds Headlamp Relay Pin 30. High-power driver steps 12V down to constant-current LED driver module.',
        sourceNode: '15A H-LP LH (Left Headlamp Fuse)',
        fuseNode: '15A H-LP LH Fuse',
        relayNode: 'HEADLAMP RELAY (H-LP)',
        wireColorCode: 'G (Green 16 AWG power feed)',
        wireColorHex: '#22c55e',
        wireGauge: '16 AWG (1.3 mm²)',
        connectorCode: 'Connector A45 (Left Headlamp 8-Pin)',
        terminalPin: 'Pin 1 (LED +12V Feed), Pin 3 (High-Beam Solenoid)',
      },
      ground: {
        summary: 'Dedicated low-resistance ground wire returns from Pin 8 to front left body crossmember ground bolt EC.',
        terminalPin: 'Connector A45 Pin 8 (GND)',
        groundPointId: 'EC (Radiator Core Support Left)',
        location: 'Behind Left Headlight Housing on Radiator Support',
        wireColorCode: 'W-B (White with Black stripe)',
        wireColorHex: '#f8fafc',
        maxResistanceOhms: 0.04,
      },
      signal: {
        summary: 'Multiplex Body ECU outputs LIN Bus control packet or 12V PWM Dimming signal to LED Light Guide for DRL / Park mode.',
        signalType: 'PWM / Duty Cycle',
        controller: 'Main Body ECU (Driver Side J/B)',
        controllerPin: 'Connector 3A Pin 14 (DRL_PWM)',
        wireColorCode: 'V-W (Violet with White stripe)',
        wireColorHex: '#a855f7',
        operatingRange: '0-100% Duty Cycle at 200 Hz (10% DRL dim, 100% Full On)',
        waveformDesc: '200 Hz PWM square wave pulse modulated for LED brightness',
      },
      relatedFuse: {
        id: 'H-LP-LH-15A',
        name: 'H-LP LH (Left Headlamp Fuse)',
        ratingAmps: 15,
        fuseType: 'Low-Profile Mini',
        locationBox: 'Engine Room Junction Block (Slot F22)',
        colorHex: '#3b82f6',
      },
      relatedRelay: {
        id: 'H-LP-RELAY',
        name: 'HEADLAMP RELAY (H-LP)',
        type: '4-Pin SPST',
        location: 'Engine Room Junction Block, Position R7',
        coilTerminals: 'Pin 85 (GND) & Pin 86 (Body ECU Headlight Command)',
        contactTerminals: 'Pin 30 (Fused B+) & Pin 87 (Output to Headlights)',
        nominalCoilOhms: 90,
      },
      relatedSensor: {
        id: 'AMBIENT-LIGHT-SENSOR',
        name: 'Automatic Headlight Dusk/Dawn Photodiode Sensor',
        partNumberOEM: '89121-30020',
        sensorTechnology: 'Optical',
        diagnosticRole: 'Monitors ambient lux levels through windshield to automatically command headlamp relay engagement.',
        normalOperatingValue: '4.8V in pitch darkness (Headlights ON); 0.4V in direct sunlight (Headlights OFF)',
      },
      testValues: {
        voltage: {
          keyOffV: 0.0,
          keyOnV: 0.0,
          runningV: 13.8, // when switch active
          vrefV: 5.0,
          nominalText: 'Pin 1: 13.8V - 14.2V when headlights switched ON; 0V when OFF',
        },
        resistance: {
          nominalOhms: 12.5,
          minOhms: 11.0,
          maxOhms: 14.5,
          testCondition: 'High-beam shutter solenoid coil between Pin 3 and Pin 8 at 20°C',
        },
        continuity: {
          testPinA: 'Connector A45 Pin 8',
          testPinB: 'Radiator Support Ground EC',
          expectedLoopOhms: 0.03,
          status: 'CONTINUITY OK (< 0.1 Ω)',
        },
        voltageDrop: {
          testCircuit: 'Battery (+) Post to Headlamp Pin 1 at 4.2A active LED operating draw',
          standardMaxV: 0.35,
          measuredDropV: 0.16,
          standardRef: 'SAE J575 Automotive Lighting Electrical Standard',
          passStatus: true,
        },
      },
      schematic: {
        nodes: [
          { id: 'f22-fuse', label: '15A H-LP Fuse', sub: 'Fused B+', x: 80, y: 120, type: 'fuse' },
          { id: 'hlp-relay', label: 'H-LP Relay', sub: 'Pin 30/87', x: 240, y: 120, type: 'relay' },
          { id: 'bcm-switch', label: 'Body ECU & Light Sw', sub: 'Lighting Logic', x: 240, y: 240, type: 'switch_ecu' },
          { id: 'led-proj', label: 'Bi-Beam LED Projector', sub: 'Front Left', x: 420, y: 120, type: 'component' },
          { id: 'gnd-ec', label: 'Ground EC', sub: 'Core Support', x: 420, y: 240, type: 'ground' },
        ],
        wires: [
          { fromNodeId: 'f22-fuse', toNodeId: 'hlp-relay', wireType: 'power', colorCode: 'G-W (16 AWG)', colorHex: '#ef4444', gaugeAwg: '16 AWG', voltageNominalV: 12.6, expectedCurrentA: 4.2 },
          { fromNodeId: 'bcm-switch', toNodeId: 'hlp-relay', wireType: 'signal', colorCode: 'V-W (20 AWG)', colorHex: '#a855f7', gaugeAwg: '20 AWG', voltageNominalV: 12.0, expectedCurrentA: 0.12 },
          { fromNodeId: 'hlp-relay', toNodeId: 'led-proj', wireType: 'power', colorCode: 'G (16 AWG)', colorHex: '#22c55e', gaugeAwg: '16 AWG', voltageNominalV: 13.8, expectedCurrentA: 4.2 },
          { fromNodeId: 'led-proj', toNodeId: 'gnd-ec', wireType: 'ground', colorCode: 'W-B (16 AWG)', colorHex: '#f8fafc', gaugeAwg: '16 AWG', voltageNominalV: 0.04, expectedCurrentA: 4.2 },
        ],
      },
    },
  ],

  ignition: [
    {
      id: 'toyota-cop-coil-1',
      systemId: 'ignition',
      nameEn: 'Cylinder #1 Direct Coil-On-Plug (COP) with Integrated Igniter',
      nameAr: 'كويل شمعة الإشعال للاسطوانة رقم 1 مع وحدة إشعال مدمجة',
      location: 'Engine Valve Cover Top, Cylinder #1 (Timing Chain End)',
      partNumberOEM: '90919-02275 (Denso Direct Ignition Coil)',
      powerPath: {
        summary: '20A INJ/IGN fuse feeds IG2 Relay, supplying continuous clean 12V B+ to Pin 1 of each 4-pin ignition coil harness connector.',
        sourceNode: '20A INJ/IGN Fuse via IG2 Relay',
        fuseNode: '20A INJ/IGN Fuse',
        relayNode: 'IG2 RELAY',
        wireColorCode: 'B-R (Black with Red stripe)',
        wireColorHex: '#dc2626',
        wireGauge: '16 AWG (1.3 mm²)',
        connectorCode: 'Connector I1 (Cylinder 1 Coil 4-Pin)',
        terminalPin: 'Pin 1 (+B Power Supply)',
      },
      ground: {
        summary: 'Pin 4 is grounded directly to cylinder head ground lug ED to sink primary coil flyback currents without EMI noise in sensors.',
        terminalPin: 'Connector I1 Pin 4 (GND)',
        groundPointId: 'ED (Engine Cylinder Head Rear Left)',
        location: 'Rear of Valve Cover Ground Stud M6',
        wireColorCode: 'W-B (White with Black stripe)',
        wireColorHex: '#f8fafc',
        maxResistanceOhms: 0.03,
      },
      signal: {
        summary: 'ECM sends 5V trigger pulse (IGT1) to Pin 2 to start primary charge, then shuts off pulse to fire spark. Coil confirms spark by pulsing Pin 3 (IGF1) back to ECM.',
        signalType: 'Ionization Feedback (IGF)',
        controller: 'ECM (Engine Control Module)',
        controllerPin: 'Connector E24 Pin 18 (IGT1) & Pin 22 (IGF1 Confirmation)',
        wireColorCode: 'L (Blue for IGT1) & G (Green for IGF1)',
        wireColorHex: '#38bdf8',
        operatingRange: 'IGT: 0V to 5.0V square pulse (2-4 ms dwell); IGF: 5V baseline with 0V confirmation drop',
        waveformDesc: '5V square dwell pulse followed by instantaneous high-voltage spark discharge',
      },
      relatedFuse: {
        id: 'IGN-20A',
        name: 'INJ/IGN (Ignition & Injectors Fuse)',
        ratingAmps: 20,
        fuseType: 'Low-Profile Mini',
        locationBox: 'Engine Room Junction Block (Slot F5)',
        colorHex: '#eab308',
      },
      relatedRelay: {
        id: 'IG2-RELAY-IGN',
        name: 'IG2 MAIN IGNITION RELAY',
        type: '4-Pin SPST',
        location: 'Engine Room Junction Block, Position R4',
        coilTerminals: 'Pin 85 (GND) & Pin 86 (Switched Ignition)',
        contactTerminals: 'Pin 30 (Fused B+) & Pin 87 (Ignition Coil B+ Feed)',
        nominalCoilOhms: 82,
      },
      relatedSensor: {
        id: 'CKP-SENSOR',
        name: 'Crankshaft Position Sensor (Crank 36-2 Trigger Wheel)',
        partNumberOEM: '90919-05089',
        sensorTechnology: 'Hall-Effect',
        diagnosticRole: 'Calculates exact piston Top Dead Center (TDC) and engine RPM to trigger IGT ignition advance timing.',
        normalOperatingValue: '0-5V digital tooth pulses matching 36-2 reluctor wheel teeth',
      },
      testValues: {
        voltage: {
          keyOffV: 0.0,
          keyOnV: 12.2,
          runningV: 14.1,
          vrefV: 5.0,
          nominalText: 'Pin 1: 12.2V Key ON; Pin 2 (IGT): 0V resting, pulses to 5.0V during crank/run',
        },
        resistance: {
          nominalOhms: 1.1,
          minOhms: 0.9,
          maxOhms: 1.4,
          testCondition: 'Primary coil winding at 20°C (between Pin 1 and Pin 4)',
        },
        continuity: {
          testPinA: 'Coil Pin 4 (GND)',
          testPinB: 'Cylinder Head Metal Ground',
          expectedLoopOhms: 0.02,
          status: 'CONTINUITY OK (< 0.1 Ω)',
        },
        voltageDrop: {
          testCircuit: 'Battery Positive to Coil Pin 1 at 7.5A peak primary dwell charge',
          standardMaxV: 0.25,
          measuredDropV: 0.09,
          standardRef: 'SAE J973 Ignition System Standard',
          passStatus: true,
        },
      },
      schematic: {
        nodes: [
          { id: 'f5-ign', label: '20A INJ/IGN Fuse', sub: 'Fused B+', x: 80, y: 110, type: 'fuse' },
          { id: 'ig2-rly', label: 'IG2 Relay', sub: 'Switched 12V', x: 220, y: 110, type: 'relay' },
          { id: 'ecm-igt', label: 'ECM IGT1 / IGF', sub: 'Dwell Timing', x: 220, y: 250, type: 'switch_ecu' },
          { id: 'cop-1', label: 'COP Ignition Coil #1', sub: '4-Pin Igniter', x: 420, y: 110, type: 'component' },
          { id: 'gnd-head', label: 'Cylinder Head Ground ED', sub: 'Engine Head', x: 420, y: 250, type: 'ground' },
        ],
        wires: [
          { fromNodeId: 'f5-ign', toNodeId: 'ig2-rly', wireType: 'power', colorCode: 'B-R (16 AWG)', colorHex: '#ef4444', gaugeAwg: '16 AWG', voltageNominalV: 12.6, expectedCurrentA: 7.5 },
          { fromNodeId: 'ig2-rly', toNodeId: 'cop-1', wireType: 'power', colorCode: 'B-R (Pin 1)', colorHex: '#dc2626', gaugeAwg: '16 AWG', voltageNominalV: 12.2, expectedCurrentA: 7.5 },
          { fromNodeId: 'ecm-igt', toNodeId: 'cop-1', wireType: 'signal', colorCode: 'L (IGT1 5V)', colorHex: '#38bdf8', gaugeAwg: '20 AWG', voltageNominalV: 5.0, expectedCurrentA: 0.01 },
          { fromNodeId: 'cop-1', toNodeId: 'gnd-head', wireType: 'ground', colorCode: 'W-B (Pin 4)', colorHex: '#f8fafc', gaugeAwg: '16 AWG', voltageNominalV: 0.03, expectedCurrentA: 7.5 },
        ],
      },
    },
  ],

  sensors: [
    {
      id: 'toyota-maf-sensor',
      systemId: 'sensors',
      nameEn: 'Mass Airflow (MAF) & Intake Air Temperature (IAT) Dual Sensor',
      nameAr: 'حساس كتلة تدفق الهواء (MAF) وحرارة هواء السحب (IAT)',
      location: 'Air Intake Duct downstream of Air Filter Housing',
      partNumberOEM: '22204-0V010 (Denso Hot-Wire Digital MAF)',
      powerPath: {
        summary: 'Pin 1 receives fused 12V B+ from 15A EFI-2 fuse to power internal platinum hot-wire heating element. Pin 3 receives ultra-precise 5.00V VREF from ECM.',
        sourceNode: '15A EFI-2 Fuse (12V) & ECM VREF (5.00V)',
        fuseNode: '15A EFI-2 Fuse',
        relayNode: 'EFI MAIN Relay',
        wireColorCode: 'B-W (12V Pin 1) & R-Y (5V VREF Pin 3)',
        wireColorHex: '#f97316',
        wireGauge: '20 AWG (0.5 mm²)',
        connectorCode: 'Connector B2 (MAF 5-Pin Sealed)',
        terminalPin: 'Pin 1 (+B 12V), Pin 3 (VREF 5V)',
      },
      ground: {
        summary: 'Sensor Signal Ground returns via Pin 2 (E2 / SIG_RTN) directly to ECM analog ground plane to eliminate chassis ground loop errors.',
        terminalPin: 'Connector B2 Pin 2 (E2 Sensor Ground)',
        groundPointId: 'ECM Pin E24-48 (Isolated Sensor Ground E2)',
        location: 'ECM Internal Shielded Ground Plane',
        wireColorCode: 'BR (Brown isolated sensor return)',
        wireColorHex: '#78350f',
        maxResistanceOhms: 0.02,
      },
      signal: {
        summary: 'Pin 4 outputs air mass flow signal (0.5V to 4.5V analog) proportional to intake air volume (grams/sec). Pin 5 outputs IAT thermistor signal.',
        signalType: '5V VREF / Analog',
        controller: 'ECM (Engine Control Module)',
        controllerPin: 'Connector E24 Pin 32 (VG / Air Mass) & Pin 33 (THA / Air Temp)',
        wireColorCode: 'Y-B (Yellow with Black stripe)',
        wireColorHex: '#facc15',
        operatingRange: '0.8V idle (2.5 g/s) to 4.2V WOT (160 g/s)',
        waveformDesc: 'Smooth analog DC voltage responding immediately to throttle plate opening',
      },
      relatedFuse: {
        id: 'EFI-2-15A',
        name: 'EFI-2 (Sensor Heater & Actuator Fuse)',
        ratingAmps: 15,
        fuseType: 'Low-Profile Mini',
        locationBox: 'Engine Room Junction Block (Slot F6)',
        colorHex: '#3b82f6',
      },
      relatedRelay: {
        id: 'EFI-MAIN-RELAY-MAF',
        name: 'EFI MAIN Relay',
        type: '4-Pin SPST',
        location: 'Engine Room Junction Block, Position R3',
        coilTerminals: 'Pin 85 (GND) & Pin 86 (Switched Power)',
        contactTerminals: 'Pin 30 (B+ Hot) & Pin 87 (Sensor +B Feed)',
        nominalCoilOhms: 84,
      },
      relatedSensor: {
        id: 'MAP-SENSOR',
        name: 'Manifold Absolute Pressure (MAP) Plausibility Sensor',
        partNumberOEM: '89421-20210',
        sensorTechnology: 'Piezoelectric',
        diagnosticRole: 'Cross-checks MAF airflow reading using Speed-Density engine calculations to detect vacuum leaks or faulty sensor calibration.',
        normalOperatingValue: '28-32 kPa at warm idle (approx. 1.2V)',
      },
      testValues: {
        voltage: {
          keyOffV: 0.0,
          keyOnV: 5.0, // VREF
          runningV: 1.2, // idle air mass
          vrefV: 5.0,
          nominalText: 'Pin 1: 12.2V; Pin 3: 5.00V ±0.05V VREF; Pin 4: 0.9V-1.3V at warm idle',
        },
        resistance: {
          nominalOhms: 2210,
          minOhms: 2000,
          maxOhms: 2500,
          testCondition: 'IAT thermistor resistance between Pin 4 and Pin 5 at 20°C',
        },
        continuity: {
          testPinA: 'MAF Pin 2 (E2)',
          testPinB: 'ECM Pin E24-48 (E2 Return)',
          expectedLoopOhms: 0.03,
          status: 'CONTINUITY OK (< 0.1 Ω)',
        },
        voltageDrop: {
          testCircuit: 'ECM 5V VREF Output to MAF Sensor Pin 3 under active load',
          standardMaxV: 0.05,
          measuredDropV: 0.015,
          standardRef: 'SAE J2716 SENT / Analog Sensor Standard',
          passStatus: true,
        },
      },
      schematic: {
        nodes: [
          { id: 'fuse-efi2', label: '15A EFI-2 Fuse', sub: '12V Power', x: 80, y: 110, type: 'fuse' },
          { id: 'ecm-vref', label: 'ECM 5.00V VREF', sub: 'Clean Reference', x: 80, y: 230, type: 'switch_ecu' },
          { id: 'maf-sens', label: 'MAF & IAT Sensor', sub: 'Connector B2', x: 300, y: 170, type: 'sensor' },
          { id: 'ecm-analog', label: 'ECM VG / THA', sub: 'ADC Inputs', x: 480, y: 170, type: 'switch_ecu' },
          { id: 'sig-rtn', label: 'Sensor Ground E2', sub: 'Isolated ECM GND', x: 480, y: 280, type: 'ground' },
        ],
        wires: [
          { fromNodeId: 'fuse-efi2', toNodeId: 'maf-sens', wireType: 'power', colorCode: 'B-W (Pin 1)', colorHex: '#ef4444', gaugeAwg: '20 AWG', voltageNominalV: 12.2, expectedCurrentA: 0.8 },
          { fromNodeId: 'ecm-vref', toNodeId: 'maf-sens', wireType: 'signal', colorCode: 'R-Y (VREF 5V)', colorHex: '#f97316', gaugeAwg: '20 AWG', voltageNominalV: 5.0, expectedCurrentA: 0.02 },
          { fromNodeId: 'maf-sens', toNodeId: 'ecm-analog', wireType: 'signal', colorCode: 'Y-B (Signal Pin 4)', colorHex: '#facc15', gaugeAwg: '20 AWG', voltageNominalV: 1.25, expectedCurrentA: 0.005 },
          { fromNodeId: 'maf-sens', toNodeId: 'sig-rtn', wireType: 'ground', colorCode: 'BR (Return Pin 2)', colorHex: '#78350f', gaugeAwg: '20 AWG', voltageNominalV: 0.01, expectedCurrentA: 0.8 },
        ],
      },
    },
  ],

  ecu: [
    {
      id: 'toyota-ecm-module',
      systemId: 'ecu',
      nameEn: 'Engine Control Module (ECM / Powertrain Micro-controller)',
      nameAr: 'وحدة التحكم في المحرك (كمبيوتر السيارة ECM)',
      location: 'Engine Bay, Front Left behind Battery',
      partNumberOEM: '89661-06Z30 (Denso 32-bit Dual-Core ECM)',
      powerPath: {
        summary: 'Constant unswitched 12V BATT from 10A ECU-B2 fuse. Switched 12V +B from 25A EFI-MAIN fuse via EFI Main Relay.',
        sourceNode: '10A ECU-B2 Fuse & 25A EFI-MAIN Fuse',
        fuseNode: '10A ECU-B2 (Constant) & 25A EFI-MAIN (Switched)',
        relayNode: 'EFI MAIN RELAY',
        wireColorCode: 'L (Blue unswitched BATT) & B-R (Black/Red switched +B)',
        wireColorHex: '#3b82f6',
        wireGauge: '18 AWG (0.8 mm²)',
        connectorCode: 'Connector E24 & E25 (128-Pin High-Density)',
        terminalPin: 'Pin E24-3 (+B), Pin E24-4 (+B2), Pin E25-1 (BATT)',
      },
      ground: {
        summary: 'Multiple independent ground pins: E01, E02 (Power Grounds) bolted to engine block EB; E1 (Logic Ground) bolted to chassis EA.',
        terminalPin: 'Pins E24-6, E24-7 (E01/E02 Power Grounds)',
        groundPointId: 'EB & EA (Block and Chassis)',
        location: 'Engine Cylinder Head Ground Stud & Fender Apron',
        wireColorCode: 'W-B (White with Black stripe)',
        wireColorHex: '#f8fafc',
        maxResistanceOhms: 0.02,
      },
      signal: {
        summary: 'Processes over 80 analog, digital, PWM, and CAN bus inputs at 1 millisecond clock cycles to control fuel injection and ignition spark.',
        signalType: 'Differential CAN (2.5V/3.5V)',
        controller: 'ECM Internal Microcontroller',
        controllerPin: 'Pins E25-41 (CAN_H) & E25-42 (CAN_L)',
        wireColorCode: 'W (CAN_H) & B (CAN_L)',
        wireColorHex: '#fbbf24',
        operatingRange: '500 kbps High-Speed CAN Bus',
        waveformDesc: 'Differential 2.0V peak-to-peak digital packets',
      },
      relatedFuse: {
        id: 'ECU-B2-10A-MOD',
        name: 'ECU-B2 (Battery Memory Keep-Alive)',
        ratingAmps: 10,
        fuseType: 'Low-Profile Mini',
        locationBox: 'Engine Room Junction Block (Slot F18)',
        colorHex: '#ef4444',
      },
      relatedRelay: {
        id: 'EFI-MAIN-RELAY-ECM',
        name: 'EFI MAIN Relay',
        type: '4-Pin SPST',
        location: 'Engine Room Junction Block, Position R3',
        coilTerminals: 'Pin 85 (GND) & Pin 86 (MREL Pin 1)',
        contactTerminals: 'Pin 30 (B+) & Pin 87 (Feeds ECM +B and +B2)',
        nominalCoilOhms: 84,
      },
      relatedSensor: {
        id: 'ACCEL-PEDAL-SENSOR',
        name: 'Accelerator Pedal Position (APP) Dual Hall Sensor',
        partNumberOEM: '78110-33060',
        sensorTechnology: 'Hall-Effect',
        diagnosticRole: 'Primary torque request input: dual independent Hall sensors with contradictory voltage slopes for drive-by-wire safety redundancy.',
        normalOperatingValue: 'Sensor 1: 0.8V to 3.8V; Sensor 2: 1.6V to 4.6V (Always exactly double V1)',
      },
      testValues: {
        voltage: {
          keyOffV: 12.6, // on BATT pin
          keyOnV: 12.2, // on +B pins
          runningV: 14.15,
          vrefV: 5.0,
          nominalText: 'Pin E25-1: 12.6V constant; Pins E24-3, E24-4: 12.2V Key ON',
        },
        resistance: {
          nominalOhms: 0.02,
          minOhms: 0.005,
          maxOhms: 0.04,
          testCondition: 'ECM Power Ground Pins E01/E02 to Battery Negative post',
        },
        continuity: {
          testPinA: 'Pin E24-6 (E01 Ground)',
          testPinB: 'Engine Block Metal Boss',
          expectedLoopOhms: 0.02,
          status: 'CONTINUITY OK (< 0.1 Ω)',
        },
        voltageDrop: {
          testCircuit: 'Battery Positive Terminal to ECM Pin E24-3 during full electrical load',
          standardMaxV: 0.2,
          measuredDropV: 0.07,
          standardRef: 'SAE J1211 Automotive Controller Reliability Standard',
          passStatus: true,
        },
      },
      schematic: {
        nodes: [
          { id: 'f18-batt', label: '10A ECU-B2', sub: 'Constant BATT', x: 80, y: 110, type: 'fuse' },
          { id: 'f2-main', label: '25A EFI Fuse & Rly', sub: 'Switched +B', x: 80, y: 220, type: 'relay' },
          { id: 'ecm-core', label: 'Denso 32-Bit ECM', sub: 'Dual-Core MCU', x: 300, y: 160, type: 'switch_ecu' },
          { id: 'can-bus-out', label: 'CAN High / Low', sub: '500 kbps Bus', x: 500, y: 110, type: 'bus' },
          { id: 'gnd-e01', label: 'Power Ground E01/E02', sub: 'Block EB', x: 500, y: 240, type: 'ground' },
        ],
        wires: [
          { fromNodeId: 'f18-batt', toNodeId: 'ecm-core', wireType: 'power', colorCode: 'L (Pin E25-1)', colorHex: '#3b82f6', gaugeAwg: '18 AWG', voltageNominalV: 12.6, expectedCurrentA: 0.05 },
          { fromNodeId: 'f2-main', toNodeId: 'ecm-core', wireType: 'power', colorCode: 'B-R (Pins E24-3/4)', colorHex: '#ef4444', gaugeAwg: '16 AWG', voltageNominalV: 12.2, expectedCurrentA: 6.5 },
          { fromNodeId: 'ecm-core', toNodeId: 'can-bus-out', wireType: 'can_high', colorCode: 'W / B (CAN H/L)', colorHex: '#fbbf24', gaugeAwg: '22 AWG', voltageNominalV: 2.5, expectedCurrentA: 0.02 },
          { fromNodeId: 'ecm-core', toNodeId: 'gnd-e01', wireType: 'ground', colorCode: 'W-B (Pins E24-6/7)', colorHex: '#f8fafc', gaugeAwg: '14 AWG', voltageNominalV: 0.02, expectedCurrentA: 6.5 },
        ],
      },
    },
  ],

  'can-bus': [
    {
      id: 'toyota-can-powertrain',
      systemId: 'can-bus',
      nameEn: 'Controller Area Network (CAN) High-Speed Powertrain Bus',
      nameAr: 'شبكة الكان باص عالية السرعة لمنظومة الدفع (Powertrain CAN)',
      location: 'Vehicle-wide twisted-pair harness connecting ECM, TCM, ABS, and DLC3',
      partNumberOEM: 'ISO 11898-2 Certified 500 kbps Shielded Twisted Pair',
      powerPath: {
        summary: 'CAN Transceivers inside each module are powered by internal 5.00V regulated power supply derived from 10A ECU-B2 fuse.',
        sourceNode: 'Internal 5.00V Transceiver Rail from ECM Power Supply',
        fuseNode: '10A ECU-B2 (Memory) & 15A ECU-IG1 (Switched Ignition)',
        relayNode: 'Internal Low-Dropout (LDO) 5V Voltage Regulator',
        wireColorCode: 'W (CAN High) & B (CAN Low twisted pair)',
        wireColorHex: '#eab308',
        wireGauge: '22 AWG Twisted Shielded Pair (1 twist per inch)',
        connectorCode: 'DLC3 (OBD-II 16-Pin Diagnostic Connector)',
        terminalPin: 'Pin 6 (CAN_H) & Pin 14 (CAN_L)',
      },
      ground: {
        summary: 'Harness shielding and module transceivers referenced to vehicle Signal Ground (DLC3 Pin 5) and Chassis Ground (DLC3 Pin 4).',
        terminalPin: 'DLC3 Pin 4 (Chassis Ground) & Pin 5 (Signal Ground)',
        groundPointId: 'IE (Instrument Panel Left Kick Panel Ground)',
        location: 'Driver Side Lower A-Pillar Ground Bolt',
        wireColorCode: 'W-B (White with Black stripe)',
        wireColorHex: '#f8fafc',
        maxResistanceOhms: 0.03,
      },
      signal: {
        summary: 'Differential digital transmission: Recessive (idle) is 2.50V on both wires. Dominant (bit 0) drives CAN_H to 3.50V and CAN_L to 1.50V.',
        signalType: 'Differential CAN (2.5V/3.5V)',
        controller: 'ECM (Engine Control Module) & Combination Meter Gateway',
        controllerPin: 'DLC3 Pin 6 (CAN_H) & DLC3 Pin 14 (CAN_L)',
        wireColorCode: 'W (CAN_H / White) & B (CAN_L / Black)',
        wireColorHex: '#f59e0b',
        operatingRange: '500 kbps baud rate (2.0V differential amplitude)',
        waveformDesc: 'Symmetrical mirrored square wave packets (CAN_H +1V, CAN_L -1V from 2.5V bias)',
      },
      relatedFuse: {
        id: 'OBD-7.5A',
        name: 'OBD (Diagnostics & DLC3 Pin 16 Power Fuse)',
        ratingAmps: 7.5,
        fuseType: 'Low-Profile Mini',
        locationBox: 'Cabin Driver-side Junction Block (Slot 12)',
        colorHex: '#a855f7',
      },
      relatedRelay: {
        id: 'IG1-RELAY-CAN',
        name: 'IG1 MAIN RELAY (Awakens all CAN Bus Transceivers)',
        type: '4-Pin SPST',
        location: 'Cabin Driver-side Junction Block, Slot R2',
        coilTerminals: 'Pin 85 (GND) & Pin 86 (Smart Key IG1 request)',
        contactTerminals: 'Pin 30 (B+) & Pin 87 (Wakes modules on CAN Bus)',
        nominalCoilOhms: 78,
      },
      relatedSensor: {
        id: 'STEERING-ANGLE-SENSOR',
        name: 'Steering Angle Sensor (SAS CAN Node)',
        partNumberOEM: '89245-06070',
        sensorTechnology: 'Optical',
        diagnosticRole: 'Broadcasts high-frequency steering wheel position and rotation speed data across CAN bus directly to VSC/ABS and EPS modules.',
        normalOperatingValue: '0.0° centered; ±540° full lock-to-lock range',
      },
      testValues: {
        voltage: {
          keyOffV: 0.0,
          keyOnV: 2.5, // Recessive baseline
          runningV: 2.65, // Active average
          vrefV: 5.0,
          nominalText: 'CAN_H: 2.5V recessive, 3.5V dominant; CAN_L: 2.5V recessive, 1.5V dominant',
        },
        resistance: {
          nominalOhms: 60,
          minOhms: 54,
          maxOhms: 66,
          testCondition: 'Between DLC3 Pin 6 (CAN_H) and Pin 14 (CAN_L) with Battery Disconnected (Two 120Ω in parallel = 60Ω)',
        },
        continuity: {
          testPinA: 'DLC3 Pin 6 (CAN_H)',
          testPinB: 'ECM Pin E25-41 (CAN_H)',
          expectedLoopOhms: 0.05,
          status: 'CONTINUITY OK (< 0.1 Ω)',
        },
        voltageDrop: {
          testCircuit: 'CAN_H End-to-End between ECM and DLC3 Diagnostic Port',
          standardMaxV: 0.1,
          measuredDropV: 0.02,
          standardRef: 'ISO 11898-2 Physical Layer Specification',
          passStatus: true,
        },
      },
      schematic: {
        nodes: [
          { id: 'ecm-term', label: 'ECM (120Ω Term Resistor)', sub: 'Node 1 Term', x: 80, y: 150, type: 'switch_ecu' },
          { id: 'abs-node', label: 'ABS / Skid Control', sub: 'CAN Node', x: 230, y: 80, type: 'component' },
          { id: 'tcm-node', label: 'Transmission TCM', sub: 'CAN Node', x: 230, y: 220, type: 'component' },
          { id: 'dlc3-port', label: 'DLC3 (OBD-II Port)', sub: 'Pin 6 & Pin 14', x: 400, y: 150, type: 'bus' },
          { id: 'meter-term', label: 'Meter Cluster (120Ω)', sub: 'Node 2 Term', x: 550, y: 150, type: 'switch_ecu' },
          { id: 'dlc-gnd', label: 'DLC3 Ground Pin 4/5', sub: 'Chassis Lug IE', x: 400, y: 280, type: 'ground' },
        ],
        wires: [
          { fromNodeId: 'ecm-term', toNodeId: 'abs-node', wireType: 'can_high', colorCode: 'W (CAN_H)', colorHex: '#fbbf24', gaugeAwg: '22 AWG', voltageNominalV: 2.5, expectedCurrentA: 0.02 },
          { fromNodeId: 'ecm-term', toNodeId: 'tcm-node', wireType: 'can_low', colorCode: 'B (CAN_L)', colorHex: '#eab308', gaugeAwg: '22 AWG', voltageNominalV: 2.5, expectedCurrentA: 0.02 },
          { fromNodeId: 'abs-node', toNodeId: 'dlc3-port', wireType: 'can_high', colorCode: 'W (CAN_H)', colorHex: '#fbbf24', gaugeAwg: '22 AWG', voltageNominalV: 2.5, expectedCurrentA: 0.02 },
          { fromNodeId: 'tcm-node', toNodeId: 'dlc3-port', wireType: 'can_low', colorCode: 'B (CAN_L)', colorHex: '#eab308', gaugeAwg: '22 AWG', voltageNominalV: 2.5, expectedCurrentA: 0.02 },
          { fromNodeId: 'dlc3-port', toNodeId: 'meter-term', wireType: 'can_high', colorCode: 'W (Twisted)', colorHex: '#fbbf24', gaugeAwg: '22 AWG', voltageNominalV: 2.5, expectedCurrentA: 0.02 },
          { fromNodeId: 'dlc3-port', toNodeId: 'dlc-gnd', wireType: 'ground', colorCode: 'W-B (Pin 4/5)', colorHex: '#f8fafc', gaugeAwg: '18 AWG', voltageNominalV: 0.01, expectedCurrentA: 0.05 },
        ],
      },
    },
  ],
};
