// AutoFix 3D - Actuator Definitions & Bidirectional Control Tests

import { ActuatorId, ActuatorTestResult } from './types';

export const INITIAL_ACTUATOR_TESTS: Record<ActuatorId, ActuatorTestResult> = {
  injector_1: {
    id: 'injector_1',
    name: 'Fuel Injector #1 Flow Balance Test',
    arabicName: 'اختبار تدفق بخاخ الوقود رقم 1',
    system: 'Fuel Delivery',
    status: 'idle',
    progressPct: 0,
    expectedCurrentA: 1.8,
    measuredCurrentA: 0.0,
    measuredResponse: 'Ready to pulse injector at 50Hz (500 pulses)',
    notes: 'Bi-directional electrical coil actuation and pressure drop measurement.',
  },
  cooling_fan_low: {
    id: 'cooling_fan_low',
    name: 'Radiator Cooling Fan Stage 1 (Low Speed)',
    arabicName: 'مروحة التبريد المرحلة 1 (سرعة منخفضة)',
    system: 'Thermal & Cooling',
    status: 'idle',
    progressPct: 0,
    expectedCurrentA: 8.5,
    measuredCurrentA: 0.0,
    measuredResponse: 'Relay K26 coil standby',
    notes: 'Actuates PWM duty cycle to 40% and verifies fan tachometer feedback.',
  },
  cooling_fan_high: {
    id: 'cooling_fan_high',
    name: 'Radiator Cooling Fan Stage 2 (High Speed)',
    arabicName: 'مروحة التبريد المرحلة 2 (سرعة عالية)',
    system: 'Thermal & Cooling',
    status: 'idle',
    progressPct: 0,
    expectedCurrentA: 22.0,
    measuredCurrentA: 0.0,
    measuredResponse: 'Relay K27 coil standby',
    notes: 'Actuates dual high-amperage cooling fan motors at 100% capacity.',
  },
  throttle_sweep: {
    id: 'throttle_sweep',
    name: 'Electronic Throttle Body 0-100% Motor Sweep',
    arabicName: 'مسح محرك الخانق الكهربائي 0-100%',
    system: 'Engine Powertrain',
    status: 'idle',
    progressPct: 0,
    expectedCurrentA: 2.4,
    measuredCurrentA: 0.0,
    measuredResponse: 'Dual potentiometer correlation check standby',
    notes: 'Checks throttle blade return spring and TPS1 vs TPS2 voltage linearity.',
  },
  fuel_pump_relay: {
    id: 'fuel_pump_relay',
    name: 'In-Tank Low-Pressure Fuel Pump Relay (EKP)',
    arabicName: 'مرحل مضخة الوقود داخل الخزان (EKP)',
    system: 'Fuel Delivery',
    status: 'idle',
    progressPct: 0,
    expectedCurrentA: 6.8,
    measuredCurrentA: 0.0,
    measuredResponse: 'Pump priming pressure standby',
    notes: 'Commands 5.5 bar low-pressure feed line priming for 5 seconds.',
  },
  abs_pump_motor: {
    id: 'abs_pump_motor',
    name: 'ABS Hydraulic Recirculation Return Pump Motor',
    arabicName: 'محرك مضخة إرجاع الزيت الهيدروليكي لنظام ABS',
    system: 'Braking & Stability',
    status: 'idle',
    progressPct: 0,
    expectedCurrentA: 14.2,
    measuredCurrentA: 0.0,
    measuredResponse: 'Hydraulic accumulator valve cycling standby',
    notes: 'Cycles solenoid inlet/outlet valves and runs high-pressure motor pump.',
  },
  starter_relay: {
    id: 'starter_relay',
    name: 'Starter Motor Solenoid Relay Diagnostic Test',
    arabicName: 'فحص مرحل بادئ الحركة (السلف)',
    system: 'Starting & Charging',
    status: 'idle',
    progressPct: 0,
    expectedCurrentA: 1.2,
    measuredCurrentA: 0.0,
    measuredResponse: 'Terminal 50 pull-in relay coil check standby',
    notes: 'Verifies ECU ignition starter interlock signal and neutral safety switch.',
  },
  horn_relay: {
    id: 'horn_relay',
    name: 'Dual Acoustic Tone Horn Relay (BCM Output)',
    arabicName: 'مرحل بوق التنبيه المزدوج (BCM)',
    system: 'Body Electronics',
    status: 'idle',
    progressPct: 0,
    expectedCurrentA: 4.5,
    measuredCurrentA: 0.0,
    measuredResponse: 'BCM High-side driver output standby',
    notes: 'Pulses 200ms acoustic horn blast to verify BCM driver and fuse.',
  },
  headlights_high: {
    id: 'headlights_high',
    name: 'Matrix LED High-Beam Actuation Test',
    arabicName: 'اختبار إضاءة الضوء العالي Matrix LED',
    system: 'Lighting System',
    status: 'idle',
    progressPct: 0,
    expectedCurrentA: 5.8,
    measuredCurrentA: 0.0,
    measuredResponse: 'Left & Right Matrix LED module communication standby',
    notes: 'Commands CAN lighting controller to illuminate all 84 LED matrix sectors.',
  },
  ac_clutch: {
    id: 'ac_clutch',
    name: 'A/C Compressor Magnetic Clutch / Solenoid Valve',
    arabicName: 'قابض كمبروسر المكيف المغناطيسي / صمام التحكم',
    system: 'HVAC & Climate',
    status: 'idle',
    progressPct: 0,
    expectedCurrentA: 3.8,
    measuredCurrentA: 0.0,
    measuredResponse: 'Refrigerant high/low pressure switch check standby',
    notes: 'Engages magnetic clutch and verifies evaporator temperature drop.',
  },
};
