// AutoFix 3D - ECU Network Definitions & Topology

import { ECUNode } from './types';

export const INITIAL_ECU_NODES: Record<string, ECUNode> = {
  ECM: {
    id: 'ECM',
    name: 'Engine Control Module (Bosch MD1CS006)',
    arabicName: 'وحدة التحكم في المحرك (ECM)',
    description: 'Master powertrain controller managing multi-point direct injection, dual VVT, ignition timing, and boost wastegates.',
    status: 'ONLINE',
    protocol: 'UDS on CAN (ISO 14229)',
    baudRate: '500 kbps (HS-CAN)',
    busChannel: 'CAN-High',
    dtcCount: 0,
    voltageV: 14.2,
    latencyMs: 12,
    hardwarePartNum: '992.906.012.F',
    softwareVersion: 'SW-8942-REV9',
  },
  TCM: {
    id: 'TCM',
    name: 'Transmission Control Module (ZF 8DT80 PDK)',
    arabicName: 'وحدة التحكم في ناقل الحركة (TCM)',
    description: 'Controls dual-clutch electro-hydraulic valve body, gear pre-selection, and shift forks.',
    status: 'ONLINE',
    protocol: 'UDS on CAN-FD',
    baudRate: '2 Mbps (Data) / 500 kbps (Nom)',
    busChannel: 'CAN-FD',
    dtcCount: 0,
    voltageV: 14.1,
    latencyMs: 14,
    hardwarePartNum: '992.927.156.B',
    softwareVersion: 'SW-PDK-4021',
  },
  ABS: {
    id: 'ABS',
    name: 'ABS / Electronic Stability Control (Bosch ESP 9.3)',
    arabicName: 'وحدة مانع الانغلاق والثبات الإلكتروني (ABS/ESP)',
    description: 'Monitors 4-wheel speed sensors, yaw rate, lateral G, and modulates hydraulic line pressure.',
    status: 'ONLINE',
    protocol: 'ISO 15765-4 CAN',
    baudRate: '500 kbps (HS-CAN)',
    busChannel: 'CAN-High',
    dtcCount: 0,
    voltageV: 14.0,
    latencyMs: 9,
    hardwarePartNum: '992.614.517.D',
    softwareVersion: 'SW-ESP93-60',
  },
  BCM: {
    id: 'BCM',
    name: 'Central Body Control Module (BCM 1)',
    arabicName: 'وحدة التحكم في هيكل السيارة والكهرباء (BCM)',
    description: 'Manages exterior lighting, central locking, power windows, immobilizer RFID antenna, and battery monitoring.',
    status: 'ONLINE',
    protocol: 'ISO 11898-2 Low-Speed Fault-Tolerant',
    baudRate: '125 kbps (MS-CAN)',
    busChannel: 'CAN-Low',
    dtcCount: 0,
    voltageV: 14.3,
    latencyMs: 24,
    hardwarePartNum: '992.907.064.A',
    softwareVersion: 'SW-BCM-1104',
  },
  SRS: {
    id: 'SRS',
    name: 'Supplemental Restraint System (Airbag Module)',
    arabicName: 'وحدة التحكم في الوسائد الهوائية (SRS)',
    description: 'Monitors front/side impact crash sensors, seatbelt pre-tensioners, and squib circuits.',
    status: 'ONLINE',
    protocol: 'ISO 14229 UDS',
    baudRate: '500 kbps',
    busChannel: 'CAN-High',
    dtcCount: 0,
    voltageV: 14.2,
    latencyMs: 8,
    hardwarePartNum: '992.959.655.C',
    softwareVersion: 'SW-SRS-SAFETY-A',
  },
  HVAC: {
    id: 'HVAC',
    name: 'Automatic Dual-Zone Climate Controller',
    arabicName: 'وحدة التحكم في نظام التكييف والحرارة (HVAC)',
    description: 'Regulates stepper blend door actuators, blower motor PWM speed, and compressor displacement valve.',
    status: 'ONLINE',
    protocol: 'LIN / CAN Gateway',
    baudRate: '125 kbps (Body Bus)',
    busChannel: 'CAN-Low',
    dtcCount: 0,
    voltageV: 13.9,
    latencyMs: 35,
    hardwarePartNum: '992.907.044.J',
    softwareVersion: 'SW-CLIM-220',
  },
  ADAS: {
    id: 'ADAS',
    name: 'Advanced Driver Assistance Systems Gateway',
    arabicName: 'وحدة أنظمة مساعدة السائق المتقدمة (ADAS)',
    description: 'Processes long-range 77GHz millimeter-wave radar and front windshield stereoscopic camera feeds for Adaptive Cruise Control.',
    status: 'ONLINE',
    protocol: 'Automotive Ethernet / CAN-FD',
    baudRate: '2 Mbps',
    busChannel: 'CAN-FD',
    dtcCount: 0,
    voltageV: 14.2,
    latencyMs: 15,
    hardwarePartNum: '992.907.572.E',
    softwareVersion: 'SW-ADAS-GEN3-L2',
  },
};
