// AutoFix 3D - Comprehensive Sensor Definitions & Diagnostic Logic

import { SensorDefinition, SensorId } from './types';

export const INITIAL_SENSOR_DEFINITIONS: Record<SensorId, SensorDefinition> = {
  maf: {
    id: 'maf',
    name: 'Mass Air Flow (MAF) Sensor',
    arabicName: 'حساس تدفق كتلة الهواء (MAF)',
    system: 'Engine Powertrain',
    subsystem: 'Air Induction',
    ecu: 'ECM',
    unit: 'g/s',
    normalMin: 2.5,
    normalMax: 180.0,
    currentValue: 4.8,
    voltage: 1.42,
    state: 'NORMAL',
    associatedDtcs: ['P0101', 'P0102', 'P0103'],
    description: 'Hot-wire anemometer measuring mass rate of air entering intake plenum for stoichiometric fuel delivery.',
  },
  o2_b1s1: {
    id: 'o2_b1s1',
    name: 'Upstream Oxygen Sensor (Bank 1, Sensor 1)',
    arabicName: 'حساس الأكسجين العلوي (بنك 1، حساس 1)',
    system: 'Emission Control',
    subsystem: 'Exhaust Gas Aftertreatment',
    ecu: 'ECM',
    unit: 'V',
    normalMin: 0.1,
    normalMax: 0.9,
    currentValue: 0.45,
    voltage: 0.45,
    state: 'NORMAL',
    associatedDtcs: ['P0130', 'P0131', 'P0132', 'P0171'],
    description: 'Zirconia wideband Lambda sensor providing closed-loop AFR feedback before catalytic converter.',
  },
  o2_b1s2: {
    id: 'o2_b1s2',
    name: 'Downstream Oxygen Sensor (Bank 1, Sensor 2)',
    arabicName: 'حساس الأكسجين السفلي (بنك 1، حساس 2)',
    system: 'Emission Control',
    subsystem: 'Catalyst Efficiency Monitor',
    ecu: 'ECM',
    unit: 'V',
    normalMin: 0.4,
    normalMax: 0.8,
    currentValue: 0.65,
    voltage: 0.65,
    state: 'NORMAL',
    associatedDtcs: ['P0136', 'P0137', 'P0420'],
    description: 'Monitors catalyst oxygen storage capacity and catalytic conversion efficiency.',
  },
  ect: {
    id: 'ect',
    name: 'Engine Coolant Temperature (ECT) Sensor',
    arabicName: 'حساس حرارة سائل تبريد المحرك (ECT)',
    system: 'Thermal & Cooling',
    subsystem: 'Engine Temperature Management',
    ecu: 'ECM',
    unit: '°C',
    normalMin: 80.0,
    normalMax: 105.0,
    currentValue: 92.0,
    voltage: 0.85,
    state: 'NORMAL',
    associatedDtcs: ['P0115', 'P0116', 'P0117', 'P0118'],
    description: 'Negative Temperature Coefficient (NTC) thermistor monitoring engine block coolant jacket.',
  },
  tps: {
    id: 'tps',
    name: 'Throttle Position Sensor (TPS A/B)',
    arabicName: 'حساس موضع الخانق الكهربائي (TPS)',
    system: 'Engine Powertrain',
    subsystem: 'Drive-by-Wire (ETC)',
    ecu: 'ECM',
    unit: '%',
    normalMin: 0.0,
    normalMax: 100.0,
    currentValue: 12.5,
    voltage: 0.92,
    state: 'NORMAL',
    associatedDtcs: ['P0120', 'P0122', 'P0123', 'P2135'],
    description: 'Dual potentiometer Hall-effect sensor tracking throttle plate angle for electronic drive-by-wire.',
  },
  ckp: {
    id: 'ckp',
    name: 'Crankshaft Position (CKP) Sensor',
    arabicName: 'حساس موضع عمود الكرنك (CKP)',
    system: 'Ignition & Timing',
    subsystem: 'Engine Synchronization',
    ecu: 'ECM',
    unit: 'RPM',
    normalMin: 600.0,
    normalMax: 7800.0,
    currentValue: 850.0,
    voltage: 2.5,
    state: 'NORMAL',
    associatedDtcs: ['P0335', 'P0336', 'P0300'],
    description: 'Reluctance or Hall sensor reading 60-2 reluctor wheel for cylinder TDC reference and misfire detection.',
  },
  frp: {
    id: 'frp',
    name: 'Fuel Rail High-Pressure (FRP) Sensor',
    arabicName: 'حساس ضغط مسطرة الوقود العالي (FRP)',
    system: 'Fuel System',
    subsystem: 'Direct Injection (GDI/DFI)',
    ecu: 'ECM',
    unit: 'bar',
    normalMin: 30.0,
    normalMax: 220.0,
    currentValue: 50.0,
    voltage: 1.65,
    state: 'NORMAL',
    associatedDtcs: ['P0190', 'P0191', 'P0192', 'P0193'],
    description: 'Piezoresistive pressure transducer on common rail monitoring mechanical high-pressure fuel pump.',
  },
  map: {
    id: 'map',
    name: 'Manifold Absolute Pressure (MAP) Sensor',
    arabicName: 'حساس الضغط المطلق لمجمع السحب (MAP)',
    system: 'Engine Powertrain',
    subsystem: 'Forced Induction / Boost',
    ecu: 'ECM',
    unit: 'kPa',
    normalMin: 28.0,
    normalMax: 260.0,
    currentValue: 34.0,
    voltage: 1.15,
    state: 'NORMAL',
    associatedDtcs: ['P0105', 'P0106', 'P0107', 'P0108'],
    description: 'Silicon micromachined diaphragm measuring manifold vacuum or positive turbo boost pressure.',
  },
  iat: {
    id: 'iat',
    name: 'Intake Air Temperature (IAT) Sensor',
    arabicName: 'حساس درجة حرارة هواء السحب (IAT)',
    system: 'Engine Powertrain',
    subsystem: 'Air Induction',
    ecu: 'ECM',
    unit: '°C',
    normalMin: 15.0,
    normalMax: 65.0,
    currentValue: 32.0,
    voltage: 2.15,
    state: 'NORMAL',
    associatedDtcs: ['P0111', 'P0112', 'P0113'],
    description: 'NTC thermistor measuring charge air temperature for air density mass calculations.',
  },
  wss_fl: {
    id: 'wss_fl',
    name: 'Front-Left Wheel Speed Sensor (WSS-FL)',
    arabicName: 'حساس سرعة العجلة الأمامية اليسرى (WSS-FL)',
    system: 'Braking & Stability',
    subsystem: 'ABS / ESC Hydraulic Module',
    ecu: 'ABS',
    unit: 'km/h',
    normalMin: 0.0,
    normalMax: 320.0,
    currentValue: 0.0,
    voltage: 1.85,
    state: 'NORMAL',
    associatedDtcs: ['C0035', 'C0040', 'U0121'],
    description: 'Active magneto-resistive wheel speed encoder feeding wheel velocity to ABS and traction control.',
  },
  bap: {
    id: 'bap',
    name: 'Brake Master Cylinder Pressure Sensor',
    arabicName: 'حساس ضغط أسطوانة الفرامل الرئيسية',
    system: 'Braking & Stability',
    subsystem: 'ABS / Brake Booster',
    ecu: 'ABS',
    unit: 'bar',
    normalMin: 0.0,
    normalMax: 180.0,
    currentValue: 2.0,
    voltage: 0.52,
    state: 'NORMAL',
    associatedDtcs: ['C0131', 'C0245'],
    description: 'Hydraulic pressure sensor measuring driver brake pedal hydraulic effort for emergency brake assist.',
  },
  sas: {
    id: 'sas',
    name: 'Steering Angle Sensor (SAS)',
    arabicName: 'حساس زاوية عجلة القيادة (SAS)',
    system: 'Suspension & Steering',
    subsystem: 'Electric Power Steering / ESP',
    ecu: 'ABS',
    unit: 'deg',
    normalMin: -540.0,
    normalMax: 540.0,
    currentValue: 0.0,
    voltage: 2.5,
    state: 'NORMAL',
    associatedDtcs: ['C0051', 'U0126'],
    description: 'Optical/magnetic steering column encoder measuring angular position and turn rate for ESP stability.',
  },
};
