import React, { useState } from 'react';
import { Language } from '../../types';
import {
  DiagnosticReportData,
  PROFESSIONAL_DISCLAIMER,
} from '../../db/diagnosticEngineData';

interface DiagnosticReportViewProps {
  report: DiagnosticReportData;
  lang: Language;
  onClose: () => void;
  onInspectIn3D?: (componentName: string) => void;
  onRestartWizard?: () => void;
}

export const DiagnosticReportView: React.FC<DiagnosticReportViewProps> = ({
  report,
  lang,
  onClose,
  onInspectIn3D,
  onRestartWizard,
}) => {
  const isAr = lang === 'ar';
  const [copied, setCopied] = useState(false);
  const [savedLocally, setSavedLocally] = useState(false);

  // Handle native browser print
  const handlePrint = () => {
    window.print();
  };

  // Handle Save to LocalStorage
  const handleSave = () => {
    try {
      const existing = localStorage.getItem('autoFix_diagnostic_reports');
      const reports = existing ? JSON.parse(existing) : [];
      reports.unshift(report);
      localStorage.setItem('autoFix_diagnostic_reports', JSON.stringify(reports.slice(0, 20)));
      setSavedLocally(true);
      setTimeout(() => setSavedLocally(false), 3000);
    } catch {
      // ignore storage error
    }
  };

  // Handle Share (Clipboard or Web Share API)
  const handleShare = async () => {
    const summaryText = `[AutoFix Diagnostic Report]
Vehicle: ${report.vehicle.year} ${report.vehicle.make} ${report.vehicle.model}
Symptom: ${report.symptom}
Diagnosis: ${report.conclusion.title} (${report.conclusion.status} - ${report.confidence}% Confidence)
Root Cause: ${report.conclusion.rootCause}
Tests Performed: ${report.testsPerformed.length}
Parts Involved: ${report.conclusion.partsInvolved.map((p) => p.name).join(', ')}
Generated by AutoFix Professional Diagnostic Engine`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: `Diagnostic Report: ${report.conclusion.title}`,
          text: summaryText,
        });
        return;
      } catch {
        // Fallback to clipboard
      }
    }

    try {
      await navigator.clipboard.writeText(summaryText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // clipboard error
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'Likely Cause':
        return 'bg-error-container text-on-error-container border-error/30';
      case 'Possible Cause':
        return 'bg-amber-500/15 text-amber-400 border-amber-500/30';
      case 'Requires Inspection':
        return 'bg-secondary/15 text-secondary border-secondary/30';
      default:
        return 'bg-surface-container-high text-on-surface';
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-black/85 backdrop-blur-lg overflow-y-auto">
      <div className="bg-surface-container-lowest border border-white/10 rounded-2xl w-full max-w-4xl shadow-2xl overflow-hidden flex flex-col my-auto max-h-[92vh]">
        {/* ACTION BAR (HIDDEN IN PRINT) */}
        <div className="p-4 bg-surface-container-low border-b border-white/5 flex flex-wrap items-center justify-between gap-3 print:hidden">
          <div className="flex items-center gap-2">
            <span className="p-1.5 rounded-lg bg-primary-container/10 text-primary-container">
              <span className="material-symbols-outlined text-lg">description</span>
            </span>
            <span className="font-headline-md text-sm font-bold text-on-surface">
              {isAr ? 'تقرير التشخيص الفني المعتمد' : 'Certified Diagnostic Report'}
            </span>
            <span className="text-outline font-code-sm text-xs">#{report.reportId}</span>
          </div>

          <div className="flex items-center gap-2">
            {/* Print Button */}
            <button
              onClick={handlePrint}
              className="px-3 py-1.5 rounded-lg bg-surface-container-high hover:bg-surface-bright text-on-surface font-code-sm text-xs font-semibold flex items-center gap-1.5 cursor-pointer transition-colors"
              title="Print formatted workshop sheet"
            >
              <span className="material-symbols-outlined text-base">print</span>
              <span>{isAr ? 'طباعة' : 'Print'}</span>
            </button>

            {/* PDF Export Button (uses print dialog with PDF intent) */}
            <button
              onClick={handlePrint}
              className="px-3 py-1.5 rounded-lg bg-surface-container-high hover:bg-surface-bright text-primary-container font-code-sm text-xs font-semibold flex items-center gap-1.5 cursor-pointer transition-colors"
              title="Export report as PDF"
            >
              <span className="material-symbols-outlined text-base">picture_as_pdf</span>
              <span>PDF</span>
            </button>

            {/* Save Button */}
            <button
              onClick={handleSave}
              className="px-3 py-1.5 rounded-lg bg-surface-container-high hover:bg-surface-bright text-on-surface font-code-sm text-xs font-semibold flex items-center gap-1.5 cursor-pointer transition-colors"
            >
              <span className="material-symbols-outlined text-base">
                {savedLocally ? 'bookmark_added' : 'bookmark'}
              </span>
              <span>
                {savedLocally
                  ? isAr
                    ? 'تم الحفظ'
                    : 'Saved!'
                  : isAr
                  ? 'حفظ'
                  : 'Save'}
              </span>
            </button>

            {/* Share Button */}
            <button
              onClick={handleShare}
              className="px-3 py-1.5 rounded-lg bg-surface-container-high hover:bg-surface-bright text-on-surface font-code-sm text-xs font-semibold flex items-center gap-1.5 cursor-pointer transition-colors"
            >
              <span className="material-symbols-outlined text-base">
                {copied ? 'done' : 'share'}
              </span>
              <span>
                {copied
                  ? isAr
                    ? 'تم النسخ!'
                    : 'Copied!'
                  : isAr
                  ? 'مشاركة'
                  : 'Share'}
              </span>
            </button>

            {/* Close Button */}
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg bg-surface-container text-outline hover:text-on-surface transition-colors cursor-pointer ms-2"
            >
              <span className="material-symbols-outlined text-lg">close</span>
            </button>
          </div>
        </div>

        {/* PRINTABLE REPORT DOCUMENT BODY */}
        <div className="p-6 sm:p-8 overflow-y-auto space-y-6 text-on-surface print:p-0 print:m-0 print:overflow-visible">
          {/* Workshop Header */}
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pb-5 border-b border-white/10">
            <div>
              <div className="flex items-center gap-2">
                <span className="text-primary font-bold text-lg tracking-wider font-headline-md">
                  AUTOFIX PRO-DIAGNOSTICS
                </span>
                <span className="px-2 py-0.5 rounded bg-primary-container/20 text-primary-container text-[10px] font-code-sm font-bold uppercase">
                  Level 3 Master Diagnostic
                </span>
              </div>
              <p className="text-xs text-outline font-code-sm mt-1">
                SAE J1979 / ISO 15031 Certified Fault Analysis System • Generated on {report.createdAt}
              </p>
            </div>

            <div className="text-end font-code-sm text-xs space-y-0.5 text-outline">
              <div>REPORT ID: <span className="text-on-surface font-bold">#{report.reportId}</span></div>
              <div>CONFIDENCE: <span className="text-primary-container font-bold">{report.confidence}%</span></div>
            </div>
          </div>

          {/* Vehicle Profile Strip */}
          <div className="bg-surface-container-low p-4 rounded-xl border border-white/5 grid grid-cols-2 sm:grid-cols-4 gap-4 text-xs font-code-sm">
            <div>
              <span className="text-outline uppercase text-[10px] font-telemetry-label">Vehicle</span>
              <div className="text-on-surface font-bold text-sm mt-0.5">
                {report.vehicle.year} {report.vehicle.make} {report.vehicle.model}
              </div>
            </div>
            <div>
              <span className="text-outline uppercase text-[10px] font-telemetry-label">Powertrain</span>
              <div className="text-on-surface font-medium mt-0.5">{report.vehicle.engine}</div>
            </div>
            <div>
              <span className="text-outline uppercase text-[10px] font-telemetry-label">Transmission</span>
              <div className="text-on-surface font-medium mt-0.5">{report.vehicle.transmission}</div>
            </div>
            <div>
              <span className="text-outline uppercase text-[10px] font-telemetry-label">VIN</span>
              <div className="text-secondary font-mono mt-0.5">{report.vehicle.vin}</div>
            </div>
          </div>

          {/* Reported Symptom Box */}
          <div className="bg-surface-container-low p-4 rounded-xl border border-white/5 space-y-1.5">
            <span className="text-outline uppercase text-[10px] font-telemetry-label flex items-center gap-1">
              <span className="material-symbols-outlined text-sm text-amber-400">report_problem</span>
              <span>Reported Primary Symptom</span>
            </span>
            <div className="text-on-surface font-bold text-base">"{report.symptom}"</div>
            <div className="flex flex-wrap items-center gap-2 pt-1 font-code-sm text-[11px] text-outline">
              <span>Candidate Systems:</span>
              {report.possibleSystems.map((sys, idx) => (
                <span key={idx} className="px-2 py-0.5 rounded bg-surface-container text-on-surface">
                  {sys}
                </span>
              ))}
            </div>
          </div>

          {/* DIAGNOSIS & ROOT CAUSE SECTION */}
          <div className="bg-surface-container-low p-5 rounded-xl border border-white/5 space-y-4">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-white/5">
              <div>
                <span className="text-[10px] font-telemetry-label text-outline uppercase">
                  Diagnostic Conclusion
                </span>
                <h3 className="font-headline-md text-lg text-on-surface font-bold mt-0.5">
                  {isAr ? report.conclusion.titleAr : report.conclusion.title}
                </h3>
              </div>

              <div className="flex items-center gap-2">
                <span
                  className={`px-3 py-1 rounded-lg border text-xs font-code-sm font-bold uppercase tracking-wider ${getStatusColor(
                    report.conclusion.status
                  )}`}
                >
                  {report.conclusion.status}
                </span>
                <span className="px-2.5 py-1 rounded-lg bg-surface-container text-primary-container font-code-sm text-xs font-bold">
                  {report.confidence}% Confidence
                </span>
              </div>
            </div>

            <div className="space-y-1.5">
              <span className="text-xs font-code-sm font-bold text-outline uppercase">Root Cause Analysis</span>
              <p className="font-body-md text-xs sm:text-sm text-on-surface leading-relaxed">
                {isAr ? report.conclusion.rootCauseAr : report.conclusion.rootCause}
              </p>
            </div>
          </div>

          {/* TESTS PERFORMED LOG (STEP-BY-STEP AUDIT TRAIL) */}
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-code-sm font-bold text-on-surface uppercase tracking-wider flex items-center gap-1.5">
                <span className="material-symbols-outlined text-base text-primary-container">fact_check</span>
                <span>Decision Tree Audit Trail ({report.testsPerformed.length} Tests Performed)</span>
              </span>
            </div>

            <div className="overflow-x-auto rounded-xl border border-white/5 bg-surface-container-low">
              <table className="w-full text-start text-xs font-code-sm">
                <thead className="bg-surface-container text-outline text-[10px] uppercase border-b border-white/5">
                  <tr>
                    <th className="p-3 text-start">#</th>
                    <th className="p-3 text-start">Test Question</th>
                    <th className="p-3 text-start">System / Component</th>
                    <th className="p-3 text-start">Expected Pass Criteria</th>
                    <th className="p-3 text-start">Actual Result</th>
                    <th className="p-3 text-end">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-white/5">
                  {report.testsPerformed.map((test, index) => (
                    <tr key={index} className="hover:bg-surface-container-high/40 transition-colors">
                      <td className="p-3 font-bold text-outline">0{index + 1}</td>
                      <td className="p-3 text-on-surface font-medium max-w-xs">{test.question}</td>
                      <td className="p-3 text-outline">
                        <div>{test.system}</div>
                        <div className="text-[10px] text-primary-container">{test.component}</div>
                      </td>
                      <td className="p-3 text-on-surface-variant max-w-xs">{test.expected}</td>
                      <td className="p-3 font-bold text-on-surface max-w-xs">{test.actual}</td>
                      <td className="p-3 text-end">
                        {test.result === 'passed' ? (
                          <span className="px-2 py-0.5 rounded bg-secondary/15 text-secondary text-[10px] font-bold uppercase">
                            PASS
                          </span>
                        ) : test.result === 'failed' ? (
                          <span className="px-2 py-0.5 rounded bg-error-container text-on-error-container text-[10px] font-bold uppercase">
                            FAIL
                          </span>
                        ) : (
                          <span className="px-2 py-0.5 rounded bg-surface-container text-outline text-[10px] font-bold uppercase">
                            INFO
                          </span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* REPAIR PROCEDURE */}
          <div className="bg-surface-container-low p-5 rounded-xl border border-white/5 space-y-3">
            <span className="text-xs font-code-sm font-bold text-on-surface uppercase tracking-wider flex items-center gap-1.5">
              <span className="material-symbols-outlined text-base text-secondary">build_circle</span>
              <span>Recommended Factory Repair Procedure</span>
            </span>

            <ol className="space-y-2 list-decimal list-inside text-xs font-body-md text-on-surface leading-relaxed">
              {(isAr ? report.conclusion.repairProcedureAr : report.conclusion.repairProcedure).map(
                (step, idx) => (
                  <li key={idx} className="ps-1">
                    <span>{step}</span>
                  </li>
                )
              )}
            </ol>
          </div>

          {/* PARTS & TOOLS REQUIRED */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {/* Parts Involved */}
            <div className="bg-surface-container-low p-4 rounded-xl border border-white/5 space-y-3">
              <span className="text-xs font-code-sm font-bold text-on-surface uppercase tracking-wider flex items-center gap-1.5">
                <span className="material-symbols-outlined text-base text-primary">inventory_2</span>
                <span>Parts Involved & Estimated Cost</span>
              </span>

              <div className="space-y-2">
                {report.conclusion.partsInvolved.map((part, pIdx) => (
                  <div
                    key={pIdx}
                    className="p-2.5 rounded-lg bg-surface-container flex items-center justify-between text-xs font-code-sm"
                  >
                    <div>
                      <div className="font-bold text-on-surface">{part.name}</div>
                      <div className="text-[10px] text-outline font-mono">P/N: {part.partNumber}</div>
                    </div>
                    <span className="text-primary-container font-bold">{part.estCost}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Tools Required & References */}
            <div className="bg-surface-container-low p-4 rounded-xl border border-white/5 space-y-3">
              <span className="text-xs font-code-sm font-bold text-on-surface uppercase tracking-wider flex items-center gap-1.5">
                <span className="material-symbols-outlined text-base text-secondary">handyman</span>
                <span>Required Diagnostic & Hand Tools</span>
              </span>

              <div className="flex flex-wrap gap-1.5">
                {report.conclusion.toolsRequired.map((tool, tIdx) => (
                  <span
                    key={tIdx}
                    className="px-2.5 py-1 rounded bg-surface-container text-on-surface text-xs font-code-sm"
                  >
                    {tool}
                  </span>
                ))}
              </div>

              <div className="pt-2 border-t border-white/5 space-y-1">
                <span className="text-[10px] font-code-sm text-outline uppercase font-bold">
                  Technical References & TSBs:
                </span>
                <div className="text-xs font-code-sm text-on-surface-variant space-y-0.5">
                  {report.conclusion.references.map((ref, rIdx) => (
                    <div key={rIdx}>• {ref}</div>
                  ))}
                </div>
              </div>
            </div>
          </div>

          {/* PROFESSIONAL DISCLAIMER (MANDATED BY PROMPT) */}
          <div className="p-4 rounded-xl bg-surface-container border border-amber-500/20 text-xs font-code-sm text-on-surface-variant space-y-1.5">
            <div className="flex items-center gap-2 text-amber-400 font-bold uppercase text-[11px]">
              <span className="material-symbols-outlined text-base">warning</span>
              <span>Professional Technician & Shop Safety Disclaimer</span>
            </div>
            <p className="leading-relaxed text-outline">
              {isAr ? PROFESSIONAL_DISCLAIMER.ar : PROFESSIONAL_DISCLAIMER.en}
            </p>
          </div>

          {/* BOTTOM FOOTER ACTIONS (HIDDEN IN PRINT) */}
          <div className="flex flex-wrap items-center justify-between gap-3 pt-4 border-t border-white/10 print:hidden">
            <div className="flex items-center gap-2">
              {onInspectIn3D && (
                <button
                  onClick={() => {
                    onInspectIn3D(report.conclusion.partsInvolved[0]?.name || 'battery');
                    onClose();
                  }}
                  className="px-4 py-2 rounded-lg bg-primary-container text-on-primary-container font-code-sm text-xs font-bold flex items-center gap-1.5 cursor-pointer shadow-[0_0_15px_rgba(0,240,255,0.3)]"
                >
                  <span className="material-symbols-outlined text-base">view_in_ar</span>
                  <span>{isAr ? 'معاينة العطل في نموذج 3D' : 'Inspect Part in 3D Rig'}</span>
                </button>
              )}

              {onRestartWizard && (
                <button
                  onClick={onRestartWizard}
                  className="px-3.5 py-2 rounded-lg bg-surface-container-high hover:bg-surface-bright text-on-surface font-code-sm text-xs font-semibold flex items-center gap-1.5 cursor-pointer"
                >
                  <span className="material-symbols-outlined text-base">restart_alt</span>
                  <span>{isAr ? 'فحص عطل جديد' : 'Diagnose Another Symptom'}</span>
                </button>
              )}
            </div>

            <button
              onClick={onClose}
              className="px-5 py-2 rounded-lg bg-surface-container hover:bg-surface-container-high text-on-surface font-code-sm text-xs font-semibold cursor-pointer"
            >
              {isAr ? 'إغلاق التقرير' : 'Close Report'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
